const fs = require('fs');
const data = JSON.parse(fs.readFileSync('src/content/m4-completo.json', 'utf8'));

data.proyecto_final = {
  "id": "m4-proyecto-final",
  "titulo": "Proyecto Final: Sistema de Prompt Engineering Profesional",
  "descripcion": "Construye un sistema completo de IA para un caso de uso real aplicando todas las técnicas del módulo. El proyecto se entrega en 5 fases evaluadas.",
  "xp_total": 500,
  "tiempo_estimado_horas": 10,
  "fases": [
    {
      "id": "fase-1",
      "numero": 1,
      "titulo": "Diagnóstico y diseño del sistema",
      "descripcion": "Identifica un problema de negocio real que puedas resolver con prompt engineering. Define los requerimientos funcionales, las métricas de éxito, y el diseño de alto nivel del sistema.",
      "xp": 80,
      "entregables": [
        "Descripción del problema de negocio (1 página): empresa o contexto, proceso actual, dolores del proceso, usuarios del sistema",
        "Métricas de éxito definidas: al menos 2 métricas cuantitativas con valor objetivo (ej: accuracy >90%, tiempo de procesamiento <30 segundos)",
        "Diseño del sistema: diagrama de flujo del proceso con IA integrada, identificación de qué hace la IA y qué hace el humano",
        "Selección justificada del modelo: por qué Claude Sonnet vs Haiku vs Opus para este caso específico"
      ],
      "criterios_evaluacion": [
        "El problema es real y específico (no genérico)",
        "Las métricas de éxito son cuantitativas y verificables",
        "El diseño separa claramente tareas de IA y tareas humanas",
        "La selección del modelo tiene justificación de costo-rendimiento"
      ],
      "recursos_recomendados": ["Lección B7-L1: Prompt Engineering para productos SaaS", "Lección B7-L3: Testing y evaluación sistemática"]
    },
    {
      "id": "fase-2",
      "numero": 2,
      "titulo": "Construcción del prompt principal",
      "descripcion": "Diseña el system prompt y los templates de prompt del sistema aplicando al menos 3 técnicas del módulo. Documenta las decisiones de diseño.",
      "xp": 100,
      "entregables": [
        "System prompt completo con al menos 3 técnicas integradas (XML tags, few-shot, CoT, role prompting, o las que apliquen al caso)",
        "Templates de prompt para los distintos tipos de input que recibirá el sistema",
        "Documento de decisiones de diseño: por qué elegiste cada técnica, qué problema específico resuelve en tu caso de uso",
        "Medidas de seguridad implementadas: cómo el prompt previene prompt injection o outputs inapropiados"
      ],
      "criterios_evaluacion": [
        "Al menos 3 técnicas del módulo aplicadas correctamente",
        "Las decisiones de diseño tienen justificación técnica específica",
        "El sistema tiene medidas básicas de seguridad documentadas",
        "Los templates son reutilizables con variables claramente definidas"
      ],
      "recursos_recomendados": ["Bloques 1-5: Técnicas de prompting", "Bloque 6: Seguridad y ética"]
    },
    {
      "id": "fase-3",
      "numero": 3,
      "titulo": "Dataset de evaluación y testing",
      "descripcion": "Construye el dataset de evaluación con al menos 30 casos de prueba y ejecuta el sistema sobre ellos. Documenta los resultados.",
      "xp": 100,
      "entregables": [
        "Dataset de 30+ casos de prueba balanceado: casos típicos (60%), edge cases (20%), adversariales (10%), fuera de alcance (10%)",
        "Resultados de ejecución: tabla con input, output esperado, output real, resultado (correcto/incorrecto)",
        "Métricas calculadas: accuracy por tipo de caso, comparación contra los objetivos definidos en Fase 1",
        "Análisis de fallos: los 5 casos donde el sistema falló más frecuentemente y por qué"
      ],
      "criterios_evaluacion": [
        "Dataset está balanceado con los 4 tipos de casos",
        "Resultados están documentados con inputs y outputs reales (no inventados)",
        "Las métricas se comparan contra los objetivos de Fase 1",
        "El análisis de fallos incluye causa raíz, no solo el síntoma"
      ],
      "recursos_recomendados": ["Lección B7-L3: Testing y evaluación sistemática", "Lección B6-L8: Auditoría de prompts"]
    },
    {
      "id": "fase-4",
      "numero": 4,
      "titulo": "Iteración y optimización",
      "descripcion": "Basándote en los resultados del testing, itera el prompt para mejorar las métricas. Documenta al menos 2 iteraciones con su razonamiento.",
      "xp": 120,
      "entregables": [
        "Versión 2 del prompt con los cambios aplicados y el razonamiento de cada cambio",
        "Comparación de métricas: V1 vs V2 en el mismo dataset de evaluación",
        "Versión 3 (opcional) si V2 no alcanzó los objetivos",
        "Reflexión de aprendizaje: qué técnica o ajuste tuvo mayor impacto y por qué"
      ],
      "criterios_evaluacion": [
        "Los cambios entre versiones están justificados con datos del testing, no con intuición",
        "La comparación de métricas usa el mismo dataset para ser válida",
        "La reflexión muestra comprensión de qué técnicas funcionaron para este caso específico",
        "Las métricas finales se acercan o superan los objetivos de Fase 1"
      ],
      "recursos_recomendados": ["Lección B7-L3: Testing y evaluación", "Lección B8-L3: Meta-prompting para optimización"]
    },
    {
      "id": "fase-5",
      "numero": 5,
      "titulo": "Documentación y presentación",
      "descripcion": "Documenta el sistema completo como si fuera para entregar a un cliente o a un equipo de desarrollo. Prepara el caso de estudio para tu portfolio.",
      "xp": 100,
      "entregables": [
        "README del sistema: propósito, arquitectura, instrucciones de uso, variables de configuración",
        "PROMPT_REGISTRY.md: versión final de todos los prompts con metadatos (versión, fecha, razón de cambios)",
        "Caso de estudio de portfolio (500 palabras): problema, solución, métricas finales, lecciones aprendidas — listo para publicar en LinkedIn",
        "Análisis de ROI: costo del sistema vs. ahorro generado con los números del proceso real"
      ],
      "criterios_evaluacion": [
        "La documentación permite a otro desarrollador entender y mantener el sistema sin preguntar",
        "El PROMPT_REGISTRY tiene historial de cambios con razones documentadas",
        "El caso de estudio tiene métricas reales y está escrito en lenguaje de negocio, no técnico",
        "El análisis de ROI usa números reales o estimaciones justificadas del proceso actual"
      ],
      "recursos_recomendados": ["Lección B7-L4: Gestión y versionado de prompts", "Lección B7-L8: Consultoría de IA"]
    }
  ]
};

data.certificacion_final = {
  "id": "m4-certificacion",
  "titulo": "Certificación M4 — Prompt Engineering Profesional",
  "descripcion": "60 preguntas que cubren todos los bloques del módulo. Se requiere 75% (45/60) para obtener la certificación.",
  "preguntas_totales": 60,
  "min_aprobacion_pct": 75,
  "min_aprobacion_num": 45,
  "tiempo_estimado_min": 90,
  "xp_aprobacion": 1000,
  "preguntas": [
    {"id":"cert-1","bloque_origen":"B0","pregunta":"¿Qué evento de 2020 marcó el inicio del Prompt Engineering como disciplina?","opciones":["Lanzamiento de BERT","Lanzamiento de GPT-3","Fundación de Anthropic","Lanzamiento de ChatGPT"],"correcta":1,"explicacion":"GPT-3 (junio 2020) fue el primer modelo que demostró que la formulación del prompt determinaba dramáticamente la calidad de la respuesta."},
    {"id":"cert-2","bloque_origen":"B0","pregunta":"¿Qué concepto fundamental de arquitectura introdujo Anthropic en el diseño de Claude?","opciones":["El tokenizador BPE","El sistema de fine-tuning masivo","El system prompt + IA Constitucional","Las redes neuronales recurrentes"],"correcta":2,"explicacion":"Anthropic introdujo el system prompt como mecanismo de control del comportamiento y la IA Constitucional como método de alineación basado en principios explícitos."},
    {"id":"cert-3","bloque_origen":"B0","pregunta":"¿Por qué el orden de la información en un prompt afecta la calidad de la respuesta?","opciones":["El modelo procesa solo las primeras 100 palabras","Los LLMs generan token por token basándose en la probabilidad condicionada por el contexto previo — la posición de la información afecta cómo se 'pondera' en la generación","El orden es irrelevante si el contenido es el mismo","El modelo solo atiende a las últimas instrucciones"],"correcta":1,"explicacion":"El mecanismo de atención en arquitecturas Transformer pondera el contexto completo, pero la posición relativa de instrucciones y datos afecta la probabilidad de los tokens generados."},
    {"id":"cert-4","bloque_origen":"B1","pregunta":"¿Cuál es la diferencia principal entre zero-shot y few-shot prompting?","opciones":["Zero-shot es más preciso que few-shot","Zero-shot no da ejemplos; few-shot incluye 1+ ejemplos de input-output para mostrar el patrón esperado","Zero-shot usa menos tokens siempre","Few-shot solo funciona con preguntas de opción múltiple"],"correcta":1,"explicacion":"Zero-shot instruye directamente sin ejemplos. Few-shot 'muestra' el patrón con ejemplos, lo que mejora la consistencia especialmente para formatos de output específicos."},
    {"id":"cert-5","bloque_origen":"B1","pregunta":"¿Cuántos ejemplos few-shot son generalmente suficientes para la mayoría de los casos de uso?","opciones":["1","3-5","20-50","100+"],"correcta":1,"explicacion":"3-5 ejemplos bien elegidos son generalmente suficientes para establecer el patrón. La ley de rendimientos decrecientes se aplica: ejemplos adicionales después de 5-7 aportan cada vez menos, aumentando el costo de tokens."},
    {"id":"cert-6","bloque_origen":"B1","pregunta":"¿Cuándo es preferible usar zero-shot sobre few-shot?","opciones":["Nunca — few-shot siempre es mejor","Cuando la tarea es simple y bien definida, cuando el modelo ya conoce bien la tarea, o cuando la inconsistencia de los ejemplos introduciría más confusión que claridad","Cuando el presupuesto de tokens es limitado solamente","Solo para preguntas de cultura general"],"correcta":1,"explicacion":"Zero-shot es preferible cuando la tarea tiene instrucción clara y el modelo la entiende bien sin ejemplos. Few-shot añade valor cuando se necesita un formato específico o comportamiento no estándar."},
    {"id":"cert-7","bloque_origen":"B1","pregunta":"¿Qué es Chain-of-Thought (CoT) prompting?","opciones":["Una técnica para encadenar múltiples prompts en secuencia","Una técnica que instruye al modelo a mostrar su proceso de razonamiento paso a paso antes de dar la respuesta final, mejorando la calidad en tareas complejas","Un método para reducir la longitud de las respuestas","Una técnica para hacer los prompts más creativos"],"correcta":1,"explicacion":"CoT fuerza al modelo a 'pensar en voz alta': externalizar el proceso de razonamiento hace que el modelo cometa menos errores lógicos y que el razonamiento sea verificable."},
    {"id":"cert-8","bloque_origen":"B1","pregunta":"'Piensa paso a paso' es un ejemplo de qué tipo de técnica?","opciones":["Role prompting","Few-shot prompting","Chain-of-Thought (CoT) prompting de forma simple","XML tagging"],"correcta":2,"explicacion":"'Piensa paso a paso' es la forma más simple de CoT: instruye al modelo a mostrar su razonamiento antes de la respuesta final. Es simple pero efectiva para una amplia gama de problemas."},
    {"id":"cert-9","bloque_origen":"B2","pregunta":"¿Cuál es el beneficio principal de usar role prompting ('actúa como un experto en X')?","opciones":["Hace al modelo más rápido","Activa un vocabulario técnico más específico, un tono apropiado para ese rol, y marcos de análisis específicos de ese dominio profesional","Permite al modelo hacer cosas que normalmente no puede","Solo mejora el estilo de escritura"],"correcta":1,"explicacion":"El role prompting no 'transforma' al modelo en otra persona, pero sí orienta la distribución de probabilidades hacia el vocabulario, el tono y los marcos conceptuales de ese rol, produciendo outputs más especializados."},
    {"id":"cert-10","bloque_origen":"B2","pregunta":"¿Qué define un rol bien especificado vs. uno genérico?","opciones":["La longitud de la descripción del rol","El nombre del rol es suficiente","Un rol bien especificado incluye: dominio de expertise, nivel de experiencia, contexto de uso y tipo de audiencia a quien responde","El uso de términos técnicos en la descripción"],"correcta":2,"explicacion":"'Eres un consultor' es genérico. 'Eres un consultor financiero senior con 15 años en fusiones y adquisiciones en Latinoamérica, respondiendo a un CFO de empresa mediana' es específico y produce outputs cualitativamente diferentes."},
    {"id":"cert-11","bloque_origen":"B2","pregunta":"¿Qué son las XML tags en el contexto del prompting y para qué sirven?","opciones":["Lenguaje de programación para crear interfaces web","Marcadores estructurales que delimitan secciones del prompt, creando separación semántica clara entre instrucciones, datos, y contexto","Una forma de comprimir el texto del prompt","Solo se usan en prompts técnicos de programación"],"correcta":1,"explicacion":"Las XML tags como <datos>, <instruccion>, <contexto> crean separación semántica que Claude puede interpretar confiablemente, reduciendo la ambigüedad sobre qué parte del prompt es instrucción y qué parte son datos a procesar."},
    {"id":"cert-12","bloque_origen":"B2","pregunta":"¿Cuándo son especialmente valiosas las XML tags?","opciones":["Solo cuando el prompt tiene más de 1000 tokens","Cuando el prompt mezcla instrucciones con datos del usuario, múltiples documentos, o contextos que el modelo necesita tratar de manera diferente","Siempre que se use la API de Claude","Solo en prompts en inglés"],"correcta":1,"explicacion":"Las XML tags brillan cuando hay riesgo de que el modelo confunda instrucciones con datos (prompt injection), cuando hay múltiples documentos con roles diferentes, o cuando el formato de output necesita ser estructurado y verificable."},
    {"id":"cert-13","bloque_origen":"B3","pregunta":"¿Qué es el prompt chaining y cuál es su beneficio principal?","opciones":["Conectar múltiples modelos de IA en serie","Dividir una tarea compleja en una secuencia de prompts donde el output de cada uno es el input del siguiente, permitiendo mejor calidad que un solo prompt complejo","Una técnica para hacer el modelo más creativo","Solo sirve para tareas de programación"],"correcta":1,"explicacion":"El prompt chaining aplica el principio de responsabilidad única: cada paso hace una cosa bien. La calidad del resultado final es superior a la de un solo prompt que intenta hacer todo a la vez."},
    {"id":"cert-14","bloque_origen":"B3","pregunta":"¿Por qué los outputs estructurados (JSON/XML) son críticos entre steps de un pipeline?","opciones":["Por preferencia estética","Para que cada step pueda parsear confiablemente el output del anterior sin ambigüedad, evitando errores de interpretación que se amplifican a lo largo del pipeline","Porque Claude solo puede generar JSON","Para reducir el número de tokens"],"correcta":1,"explicacion":"Los outputs estructurados son las interfaces entre steps: definen exactamente cómo se pasan los datos. Los outputs de texto libre introducen ambigüedad que se convierte en error en el siguiente step."},
    {"id":"cert-15","bloque_origen":"B3","pregunta":"¿Cuál es la ventaja del CoT guiado (con pasos explícitos) sobre el CoT simple ('piensa paso a paso')?","opciones":["El CoT guiado es más corto","El CoT guiado define exactamente qué pasos de razonamiento seguir, asegurando que el modelo considere todos los ángulos relevantes del problema sin omitir análisis críticos","El CoT simple produce mejores resultados en todos los casos","No hay diferencia práctica entre ambos"],"correcta":1,"explicacion":"El CoT guiado es como darle al modelo una checklist de análisis: Paso 1 (evalúa X), Paso 2 (considera Y), Paso 3 (calcula Z). Esto previene que el modelo omita análisis importantes que el diseñador considera críticos para el caso de uso."},
    {"id":"cert-16","bloque_origen":"B4","pregunta":"¿Qué es Extended Thinking en Claude y qué lo diferencia del CoT estándar?","opciones":["Es solo un nombre diferente para CoT","Extended Thinking es un proceso interno de razonamiento con un presupuesto de tokens dedicado donde el modelo puede explorar ideas, reconsiderar, y revisar — no visible al usuario final como el CoT estándar","Extended Thinking solo funciona para matemáticas","Es una versión más lenta del modelo"],"correcta":1,"explicacion":"Extended Thinking usa un espacio de 'borrador mental' interno donde el modelo puede explorar hipótesis, identificar contradicciones y revisar su razonamiento antes de generar la respuesta final. Es más profundo que el CoT estándar porque el 'borrador' no está optimizado para ser legible."},
    {"id":"cert-17","bloque_origen":"B4","pregunta":"¿Para qué tipo de tareas aporta más valor Extended Thinking?","opciones":["Clasificación simple de textos","Tareas que requieren razonamiento profundo, análisis multivariable, resolución de problemas ambiguos o decisiones estratégicas complejas donde la reflexión adicional mejora la calidad","Resumen de documentos cortos","Traducción de idiomas"],"correcta":1,"explicacion":"Extended Thinking tiene mayor ROI en tareas donde el modelo necesita 'descartar caminos equivocados' antes de llegar a la respuesta correcta. Para clasificación simple, el costo adicional no se justifica."},
    {"id":"cert-18","bloque_origen":"B4","pregunta":"¿Qué parámetro controla la profundidad del razonamiento en Extended Thinking?","opciones":["temperature","max_tokens","budget_tokens (el presupuesto de tokens para el proceso de razonamiento interno)","top_p"],"correcta":2,"explicacion":"budget_tokens define cuántos tokens puede usar el modelo en su proceso de razonamiento interno. Un presupuesto mayor permite explorar más ángulos del problema; un presupuesto menor es más rápido y económico."},
    {"id":"cert-19","bloque_origen":"B5","pregunta":"¿Cuál es el principio fundamental detrás de todas las técnicas avanzadas de prompting?","opciones":["Usar el mayor número de palabras posible","Comunicar con precisión y claridad qué se quiere, qué contexto existe, qué formato se necesita, y cómo verificar que el resultado es correcto","Usar siempre el modelo más grande disponible","Copiar prompts que funcionaron para otros casos de uso"],"correcta":1,"explicacion":"Todas las técnicas avanzadas son variaciones del mismo principio: reducir la ambigüedad en la comunicación entre humano y modelo. XML tags reducen ambigüedad estructural; few-shot reduce ambigüedad de formato; CoT reduce ambigüedad de proceso."},
    {"id":"cert-20","bloque_origen":"B5","pregunta":"Cuando se combinan múltiples técnicas en un prompt complejo, ¿cuál es el criterio correcto para decidir qué incluir?","opciones":["Incluir todas las técnicas conocidas para máxima calidad","Incluir cada técnica solo si resuelve un problema específico identificado en este caso de uso — la complejidad del prompt debe justificarse con mejoras medibles de calidad","Nunca combinar más de 2 técnicas","Usar solo las técnicas más recientes"],"correcta":1,"explicacion":"Más técnicas no equivale a mejores resultados. Cada técnica añade complejidad y costo. El criterio es: ¿qué problema específico resuelve esta técnica en este caso? Si no hay un problema específico que resolver, la técnica no debe estar ahí."},
    {"id":"cert-21","bloque_origen":"B6","pregunta":"¿Cuál es la diferencia entre prompt injection directa e indirecta?","opciones":["No hay diferencia práctica","Directa: el atacante tiene acceso al prompt y lo manipula directamente. Indirecta: instrucciones maliciosas están embebidas en datos externos (emails, documentos, páginas web) que el sistema procesa automáticamente","La indirecta es siempre más fácil de detectar","Solo la indirecta es realmente peligrosa"],"correcta":1,"explicacion":"La indirecta es generalmente más peligrosa en producción porque el atacante no necesita acceso al sistema — solo necesita que su contenido sea procesado por el agente IA."},
    {"id":"cert-22","bloque_origen":"B6","pregunta":"¿Cuál es la defensa más efectiva contra prompt injection en un sistema que procesa documentos externos?","opciones":["Usar modelos más grandes","XML tags para separar instrucciones de datos + instrucción explícita de tratar el contenido como texto a analizar, nunca como comandos a ejecutar","Revisar manualmente cada documento","Usar solo documentos internos de la empresa"],"correcta":1,"explicacion":"La defensa por capas es clave: separación semántica + instrucción explícita de tratamiento de datos + mínimo privilegio del agente."},
    {"id":"cert-23","bloque_origen":"B6","pregunta":"¿Qué es el sesgo de confirmación en LLMs y cómo se mitiga?","opciones":["El modelo confirma todo lo que el usuario dice para ser útil","El modelo tiende a generar outputs que validan la premisa implícita del prompt — se mitiga reformulando preguntas de forma neutral sin presuponer la respuesta","Es solo un problema en modelos pequeños","No se puede mitigar"],"correcta":1,"explicacion":"Si el prompt dice 'explica por qué X es mejor que Y', el modelo tenderá a confirmar que X es mejor. Reformular como 'compara X e Y en estos criterios' elimina la premisa sesgada."},
    {"id":"cert-24","bloque_origen":"B6","pregunta":"¿Qué datos NUNCA deben incluirse en prompts sin un marco legal apropiado?","opciones":["Solo contraseñas y tokens de API","PII completo (nombre+DNI+dirección+teléfono en combinación), datos de salud, datos financieros específicos, credenciales, y datos bajo NDA","Solo datos de tarjetas de crédito","No hay restricciones si el modelo es de una empresa confiable"],"correcta":1,"explicacion":"La regla es de mínimo privilegio de datos: el modelo solo debe recibir la información mínima necesaria para la tarea, anonimizada cuando sea posible, y con los acuerdos contractuales apropiados para datos sensibles."},
    {"id":"cert-25","bloque_origen":"B6","pregunta":"¿Qué son las alucinaciones en LLMs y cuál es su causa técnica principal?","opciones":["Errores de programación en el modelo","El modelo genera texto plausible y confiado pero factualmente incorrecto porque su proceso generativo es probabilístico, no de verificación factual","Solo ocurren con preguntas sobre temas oscuros","Las alucinaciones son siempre detectables por el usuario"],"correcta":1,"explicacion":"Los LLMs generan el token más probable dado el contexto, no el token más correcto. Cuando el modelo no tiene información precisa, genera la secuencia estadísticamente plausible, que puede ser factualmente incorrecta."},
    {"id":"cert-26","bloque_origen":"B6","pregunta":"¿Qué es RAG (Retrieval Augmented Generation) y por qué reduce las alucinaciones?","opciones":["Una técnica para hacer el modelo más creativo","Un enfoque donde se recuperan documentos verificables de una base de datos y se proveen como contexto al modelo, anclando sus respuestas a fuentes reales en vez de a su memoria de entrenamiento","Un método para entrenar modelos con datos nuevos","RAG solo funciona con documentos en inglés"],"correcta":1,"explicacion":"RAG elimina la dependencia de la 'memoria' del modelo: en vez de '¿qué recuerdas sobre X?', el modelo responde basándose en los documentos específicos provisionados, verificables y actualizados."},
    {"id":"cert-27","bloque_origen":"B6","pregunta":"¿Qué es la IA Constitucional de Anthropic?","opciones":["Una ley regulatoria que Anthropic debe cumplir","Un enfoque de entrenamiento donde el modelo internaliza un conjunto de principios éticos como parte de su carácter, no como restricciones externas","Un sistema de filtros de palabras clave","Solo aplica a Claude Opus, no a otros modelos"],"correcta":1,"explicacion":"La IA Constitucional entrena a Claude con principios que el modelo internaliza como propios, haciendo su comportamiento ético más robusto que sistemas con listas de reglas o filtros que pueden eludirse."},
    {"id":"cert-28","bloque_origen":"B6","pregunta":"¿Cuál es la distinción legal crítica entre 'información legal' y 'asesoría legal' en el contexto de sistemas de IA?","opciones":["No hay distinción, son lo mismo","Información legal: explicar qué dice la ley en general (no regulado). Asesoría legal: recomendar qué hacer en el caso específico de una persona (regulado, requiere licencia de abogado)","La distinción solo aplica en Estados Unidos","Solo importa si el sistema cobra dinero por sus respuestas"],"correcta":1,"explicacion":"Un chatbot puede explicar qué dice la ley (información legal); pero recomendar qué hacer en el caso específico del usuario constituye asesoría legal regulada que requiere licencia profesional."},
    {"id":"cert-29","bloque_origen":"B6","pregunta":"¿Qué es el 'red team testing' en sistemas de IA?","opciones":["Pruebas de rendimiento bajo alta carga","Un equipo adversarial que deliberadamente intenta encontrar fallos de seguridad, producir outputs dañinos, o explotar vulnerabilidades — simulando actores maliciosos reales","Pruebas de la interfaz de usuario","Revisión del código fuente del sistema"],"correcta":1,"explicacion":"El red team testing adopta la mentalidad del atacante para revelar vulnerabilidades antes de que lleguen a producción. Es la diferencia entre descubrir un fallo tú mismo en testing vs. que lo descubra un usuario malintencionado en producción."},
    {"id":"cert-30","bloque_origen":"B6","pregunta":"¿Cuál es el primer criterio para decidir si usar RAG vs. pasar el documento completo en el contexto?","opciones":["El tamaño del presupuesto de API","Si la respuesta requiere coherencia global del documento (usar contexto completo) o si puede responderse con un fragmento específico (usar RAG, más económico)","RAG siempre es preferible al contexto completo","El contexto completo siempre es preferible a RAG"],"correcta":1,"explicacion":"RAG es eficiente cuando la respuesta depende de un fragmento localizado. El contexto completo es necesario cuando la respuesta requiere síntesis de múltiples partes del documento (detectar contradicciones, análisis holístico)."},
    {"id":"cert-31","bloque_origen":"B7","pregunta":"¿Por qué los prompts en producción deben versionarse igual que el código?","opciones":["Solo por razones de auditoría regulatoria","Porque los cambios al prompt modifican el comportamiento del producto tan significativamente como los cambios al código, y necesitan el mismo control de versiones, rollback capability e historial de cambios","Solo si el producto tiene más de 10,000 usuarios","No es necesario — los prompts son más simples que el código"],"correcta":1,"explicacion":"Un prompt en producción ES código: determina el comportamiento de una feature, puede romper cosas si cambia, y necesita poder hacer rollback. La misma ingeniería de software se aplica."},
    {"id":"cert-32","bloque_origen":"B7","pregunta":"¿Cuál es la principal ventaja de los 'templates de prompt' con variables en un producto SaaS?","opciones":["Reducen el número de llamadas a la API","Permiten personalización masiva con mantenimiento centralizado: cambiar el template actualiza el comportamiento para todos los casos que lo usan, en vez de actualizar prompts individuales","Solo aplican para productos con más de 1000 usuarios","Hacen el código más legible"],"correcta":1,"explicacion":"Un template con {variables} permite: personalizar el prompt para cada cliente/contexto en runtime, mantener el comportamiento base en un solo lugar, y cambiar el comportamiento de todos los casos actualizando el template."},
    {"id":"cert-33","bloque_origen":"B7","pregunta":"¿Qué debe contener un dataset de evaluación completo para un prompt de producción?","opciones":["Solo los casos de uso más comunes","Casos representativos del uso típico (60%), edge cases (20%), casos adversariales (10%), y casos de incertidumbre/fuera de alcance (10%)","Solo los casos donde el sistema actual falla","Al menos 1000 casos para ser estadísticamente válido"],"correcta":1,"explicacion":"La distribución balanceada garantiza que el dataset represente todo el espacio de inputs que el sistema encontrará en producción, incluyendo los casos menos comunes pero potencialmente más dañinos."},
    {"id":"cert-34","bloque_origen":"B7","pregunta":"¿Cuál es la trampa más común al definir métricas para evaluar prompts en producción?","opciones":["Usar demasiadas métricas simultáneamente","Optimizar para la métrica más fácil de medir automáticamente (porcentaje de JSON válido) en vez de la que más importa para el negocio (utilidad real para el usuario)","No usar ninguna métrica cuantitativa","Solo usar feedback de usuarios finales"],"correcta":1,"explicacion":"La métrica más medible no siempre es la más importante. El diseño correcto: primero definir qué es éxito para el usuario/negocio, luego construir métricas que lo aproximen."},
    {"id":"cert-35","bloque_origen":"B7","pregunta":"¿Cuándo tiene sentido económico usar Claude Haiku 4.5 vs Sonnet 4.6?","opciones":["Siempre — Haiku es siempre suficientemente bueno","Para tareas simples y bien definidas (clasificación, extracción estructurada) donde Haiku produce resultados equivalentes a Sonnet a ~5x menor costo","Solo en entornos de desarrollo","Nunca en producción — el ahorro no justifica el riesgo"],"correcta":1,"explicacion":"La selección del modelo correcto para cada tarea es una de las optimizaciones de costo más impactantes. Haiku para lo simple, Sonnet para lo complejo, Opus para lo que requiere máximo razonamiento."},
    {"id":"cert-36","bloque_origen":"B7","pregunta":"¿Qué es el 'prompt caching' de Anthropic y cuándo aporta mayor valor?","opciones":["Guardar los prompts en localStorage del navegador","Una función de la API que almacena en caché system prompts largos y estáticos, reduciendo hasta 90% el costo de esos tokens en requests repetidos","Comprimir automáticamente los prompts","Solo disponible en el plan Enterprise"],"correcta":1,"explicacion":"El prompt caching tiene mayor impacto cuando hay un system prompt largo (500+ tokens) que se repite en miles de requests. El token cacheado tiene un costo mucho menor que el token procesado nuevamente."},
    {"id":"cert-37","bloque_origen":"B7","pregunta":"¿Qué es el 'principio de mínimo privilegio' aplicado a agentes de IA?","opciones":["El agente debe usar el modelo más barato","El agente solo debe tener acceso a las herramientas estrictamente necesarias para su tarea específica, limitando el daño potencial si el agente falla o es comprometido","El agente debe hacer el menor número de llamadas posible","Los agentes no deben tener acceso a herramientas externas"],"correcta":1,"explicacion":"Si el agente solo puede leer datos, un fallo o ataque solo puede leer datos — no puede escribir, eliminar ni enviar. El mínimo privilegio es el principal mecanismo de seguridad en sistemas agénticos."},
    {"id":"cert-38","bloque_origen":"B7","pregunta":"¿Por qué las acciones irreversibles en agentes IA requieren confirmación explícita antes de ejecutarse?","opciones":["Por razones legales únicamente","Porque un error de interpretación del agente puede ejecutar una acción que no se puede deshacer (enviar email, eliminar datos, hacer un pago), causando daño real antes de que el humano pueda intervenir","Es una preferencia de UX, no un requisito de seguridad","Solo si el agente tiene acceso a sistemas financieros"],"correcta":1,"explicacion":"El protocolo de confirmación es el seguro contra errores de interpretación: el agente resume qué va a hacer, el humano confirma, y solo entonces se ejecuta. Esto previene consecuencias irreversibles de malentendidos."},
    {"id":"cert-39","bloque_origen":"B7","pregunta":"¿Cuál es el beneficio de Claude con capacidades multimodales para análisis de estados financieros?","opciones":["Puede procesar documentos más rápido que en texto","Puede analizar tablas, gráficos y texto en una sola llamada, extrayendo datos de formatos mixtos que serían difíciles de procesar con herramientas solo de texto","La multimodalidad reduce el costo de los tokens","Solo funciona con documentos en inglés"],"correcta":1,"explicacion":"Los estados financieros combinan tablas numéricas, gráficos de tendencias y texto explicativo. La multimodalidad permite extraer datos de todos estos formatos en una sola llamada, manteniendo el contexto entre ellos."},
    {"id":"cert-40","bloque_origen":"B7","pregunta":"En una propuesta de consultoría de IA, ¿qué elemento tiene más impacto en la decisión de compra del cliente?","opciones":["La lista detallada de tecnologías que se usarán","El análisis de ROI con números concretos del proceso actual del cliente y el tiempo de recuperación de la inversión","El CV del consultor y sus certificaciones","La cantidad de páginas de la propuesta"],"correcta":1,"explicacion":"Los tomadores de decisión (CEO, CFO) aprueban proyectos basándose en el retorno de la inversión, no en la sofisticación técnica. Traducir el proyecto a 'ahorro de X por mes, inversión recuperada en Y meses' es lo que convierte una propuesta en un contrato."},
    {"id":"cert-41","bloque_origen":"B8","pregunta":"¿Qué es el efecto 'lost in the middle' en contextos largos y cómo se mitiga?","opciones":["El modelo pierde el contexto después de cierto número de tokens","Los LLMs atienden mejor al inicio y al final del contexto, perdiendo información crítica en el medio — se mitiga colocando información importante al inicio y/o al final (técnica del 'sándwich')","Es un error de Anthropic que se corregirá","Solo afecta a documentos de más de 100K tokens"],"correcta":1,"explicacion":"La mitigación más efectiva es la técnica del sándwich: instrucciones críticas al inicio + documento + instrucciones repetidas al final. El modelo verá la información importante en ambas posiciones de alta atención."},
    {"id":"cert-42","bloque_origen":"B8","pregunta":"¿Para qué tipo de análisis documental es imprescindible la ventana de 200K tokens vs. fragmentar el documento?","opciones":["Siempre — más contexto siempre es mejor","Para análisis que requieren coherencia global (detectar contradicciones entre secciones lejanas, análisis comparativo de múltiples partes del documento) donde fragmentar perdería el contexto cruzado","Para documentos en español","Solo para documentos de más de 1000 páginas"],"correcta":1,"explicacion":"Si la respuesta requiere comparar la cláusula 3 con la cláusula 87, ambas deben estar en el mismo contexto. Fragmentar el documento haría imposible detectar la relación entre secciones lejanas."},
    {"id":"cert-43","bloque_origen":"B8","pregunta":"¿Cuál es el caso de uso más apropiado para Computer Use en su fase actual (beta)?","opciones":["Reemplazar todas las integraciones de API existentes","Automatizar tareas en software legacy sin API disponible, donde la automatización por interfaz gráfica es la única opción viable con ROI suficiente para justificar las limitaciones actuales","Testing de todas las aplicaciones web","Solo para demostraciones técnicas"],"correcta":1,"explicacion":"Computer Use tiene limitaciones reales (velocidad, costo, fiabilidad en interfaces complejas). El caso de uso óptimo actual es el software legacy sin API donde el ROI de la automatización supera claramente las limitaciones."},
    {"id":"cert-44","bloque_origen":"B8","pregunta":"¿Qué información debe proveer un briefing de meta-prompting para obtener un prompt de calidad?","opciones":["Solo el nombre de la tarea","Contexto completo del caso de uso: quiénes son los usuarios, objetivo exacto, formato de output requerido, comportamientos críticos e innegociables, y ejemplos de inputs representativos","Solo los ejemplos de input/output","El presupuesto de tokens disponible"],"correcta":1,"explicacion":"El meta-prompting produce calidad proporcional al briefing. Un briefing detallado produce un prompt específico y bien diseñado; un briefing vago produce un prompt genérico que puede no ser útil para el caso de uso real."},
    {"id":"cert-45","bloque_origen":"B8","pregunta":"¿Qué es el 'checklist washing' en flujos humano+IA?","opciones":["Cuando la IA limpia datos de listas de verificación","Cuando un humano aprueba formalmente el output de la IA sin realmente revisarlo, creando la ilusión de supervisión sin el beneficio real del juicio humano","Una técnica para simplificar la revisión de outputs largos","Una práctica recomendada de control de calidad"],"correcta":1,"explicacion":"El checklist washing es uno de los riesgos más graves de los sistemas humano+IA: el humano asume la responsabilidad legal sin ejercer el juicio que la justifica. Los errores pasan sin detección y el sistema tiene la ilusión de supervisión sin la realidad."},
    {"id":"cert-46","bloque_origen":"B8","pregunta":"¿Cuál es la estrategia más efectiva para mantenerse actualizado en prompt engineering?","opciones":["Seguir influencers de IA en redes sociales","Implementar experimentos prácticos con cada nueva capacidad cuando se lanza, construyendo prototipos con casos de uso reales de tu trabajo","Hacer un nuevo curso completo de IA cada 6 meses","Leer todos los papers académicos mensualmente"],"correcta":1,"explicacion":"La brecha entre 'conocer que existe una capacidad' y 'saber cómo implementarla en producción' solo se cierra con práctica. El prototipo rápido con datos reales es el aprendizaje más efectivo."},
    {"id":"cert-47","bloque_origen":"B8","pregunta":"¿Por qué el streaming mejora la experiencia percibida del usuario aunque el tiempo total de generación sea el mismo?","opciones":["Porque el streaming genera menos tokens totales","Porque el primer token llega en ~0.5 segundos vs. esperar 15-30 segundos con la pantalla en blanco — el tiempo percibido de espera es significativamente menor cuando el usuario empieza a leer inmediatamente","Porque el streaming comprime la respuesta","El streaming no mejora la experiencia percibida"],"correcta":1,"explicacion":"La psicología del tiempo de espera muestra que el tiempo percibido (cuándo empieza a llegar contenido) importa más que el tiempo real (cuándo está completa la respuesta)."},
    {"id":"cert-48","bloque_origen":"B8","pregunta":"¿Cuál es la ventaja competitiva más durable para un prompt engineer en el mercado latinoamericano?","opciones":["Conocer todas las últimas técnicas de prompting","Combinar expertise técnico en prompt engineering con conocimiento profundo de una industria vertical específica, resolviendo problemas que un generalista no puede — con portfolio de casos reales y métricas","Tener certificaciones de los mejores proveedores de IA","Hablar inglés para acceder a información técnica antes"],"correcta":1,"explicacion":"La especialización vertical + portfolio con métricas reales es difícil de replicar rápidamente. Un prompt engineer con 10 proyectos reales en fintech con métricas documentadas tiene una ventaja competitiva que un recién egresado de un curso no puede igualar inmediatamente."},
    {"id":"cert-49","bloque_origen":"B1","pregunta":"Un prompt de extracción de información de documentos produce resultados inconsistentes. ¿Cuál es la primera técnica a aplicar?","opciones":["Cambiar a un modelo más grande","Añadir 3-5 ejemplos few-shot que muestren exactamente el formato de extracción esperado para distintos tipos de documentos del corpus real","Pedir al modelo que piense más despacio","Fragmentar el documento en partes más pequeñas"],"correcta":1,"explicacion":"La inconsistencia en extracción estructurada es la señal clásica de que el modelo no tiene suficiente contexto sobre el formato esperado. Few-shot con ejemplos del corpus real elimina la ambigüedad de formato."},
    {"id":"cert-50","bloque_origen":"B2","pregunta":"¿Qué técnica del módulo es más adecuada para analizar un problema legal complejo con múltiples perspectivas?","opciones":["Zero-shot con una pregunta directa","Role prompting combinado con CoT: 'Eres un abogado corporativo senior. Analiza este contrato paso a paso considerando: (1) riesgos para el cliente, (2) fortalezas de la posición, (3) puntos de negociación'","Few-shot con ejemplos de análisis similares","XML tags para estructurar el contrato"],"correcta":1,"explicacion":"Role prompting activa el marco conceptual del dominio legal; CoT guiado asegura que se consideren todos los ángulos relevantes. La combinación produce un análisis más completo y especializado que cualquiera de las dos técnicas solas."},
    {"id":"cert-51","bloque_origen":"B3","pregunta":"¿En qué situación es preferible un pipeline de 4 steps sobre un único prompt complejo?","opciones":["Siempre — los pipelines son siempre superiores","Cuando la tarea tiene etapas claramente diferenciadas, cada etapa requiere un tipo diferente de procesamiento, y la calidad de cada etapa determina la calidad de las siguientes","Solo cuando se trabaja con documentos de más de 10 páginas","Solo en sistemas de producción, no en prototipos"],"correcta":1,"explicacion":"El pipeline añade complejidad de ingeniería. Solo vale la pena cuando la tarea tiene responsabilidades claramente separables y la calidad mejora mediblemente al separarlas. Una tarea simple no necesita pipeline."},
    {"id":"cert-52","bloque_origen":"B4","pregunta":"¿Qué presupuesto de tokens mínimo recomienda Anthropic para Extended Thinking en tareas que requieren razonamiento profundo?","opciones":["500 tokens","1,024 tokens (mínimo recomendado para tareas de razonamiento real)","5,000 tokens","Sin mínimo recomendado"],"correcta":1,"explicacion":"Con menos de 1,024 tokens de budget_tokens, Extended Thinking no tiene suficiente espacio para explorar hipótesis y reconsiderar. Para análisis complejos (estratégicos, legales, técnicos), 8,000-16,000 tokens permiten razonamiento profundo."},
    {"id":"cert-53","bloque_origen":"B5","pregunta":"¿Qué problema resuelve la combinación de XML tags + few-shot en un sistema de extracción de datos de múltiples tipos de documentos?","opciones":["Reduce el tiempo de respuesta del modelo","XML tags delimitan claramente qué parte del prompt son datos vs. instrucciones (previniendo injection), mientras few-shot muestra el patrón de extracción esperado para cada tipo de documento (reduciendo inconsistencias de formato)","Solo mejora el rendimiento con documentos en inglés","Permite usar el modelo sin system prompt"],"correcta":1,"explicacion":"La combinación ataca dos problemas distintos: seguridad (XML tags previenen que el modelo interprete datos como instrucciones) y consistencia (few-shot reduce la variabilidad en el formato del output)."},
    {"id":"cert-54","bloque_origen":"B6","pregunta":"¿Cuál es la diferencia entre los comportamientos 'fijos' y 'configurables' de Claude según Anthropic?","opciones":["Los fijos son para uso personal, los configurables para empresas","Fijos: Claude siempre/nunca los hace independientemente de instrucciones (ej: nunca generar CSAM). Configurables: operadores pueden activar/desactivar dentro de límites éticos según su contexto legítimo","Los configurables cuestan más","No hay distinción — todo es configurable con el system prompt correcto"],"correcta":1,"explicacion":"La arquitectura de capas de Claude permite personalización extensiva dentro de límites absolutos. Los operadores tienen un espacio amplio de configuración; los límites absolutos no son negociables por ningún operador."},
    {"id":"cert-55","bloque_origen":"B6","pregunta":"¿Por qué la asesoría de inversiones personalizadas por un chatbot de IA en Colombia requiere registro ante la Superintendencia Financiera?","opciones":["Solo si el chatbot cobra dinero directamente","Porque la asesoría de inversiones personalizadas es una actividad regulada en Colombia independientemente de si la ejecuta un humano o un sistema de IA — el medio tecnológico no exime del requisito regulatorio","Solo si maneja activos de más de $100M","No requiere registro — los chatbots no son asesores financieros por definición"],"correcta":0,"explicacion":"La actividad regulada es la asesoría de inversiones personalizadas, no el medio por el cual se entrega. Una empresa que usa IA para recomendar portafolios específicos a clientes está realizando una actividad regulada."},
    {"id":"cert-56","bloque_origen":"B7","pregunta":"¿Qué elemento se omite con más frecuencia en propuestas de proyectos de IA y puede crear conflictos post-entrega?","opciones":["El cronograma de desarrollo","El costo de mantenimiento continuo: actualizaciones del prompt cuando el modelo se actualiza, gestión de nuevos edge cases en producción, y monitoreo de métricas de calidad","La lista de tecnologías usadas","Las condiciones de pago"],"correcta":1,"explicacion":"Un sistema de IA en producción requiere mantenimiento continuo. Sin incluirlo en la propuesta, el cliente esperará updates gratuitos y el consultor se verá atrapado haciendo trabajo no presupuestado."},
    {"id":"cert-57","bloque_origen":"B7","pregunta":"¿Cuál es la primera acción al implementar gestión de prompts en una empresa con 25 prompts sin estructura?","opciones":["Comprar una herramienta especializada de prompt management","Hacer un inventario de todos los prompts actuales: su propósito, dónde se usan, quién los mantiene, y la versión en producción","Reescribir todos los prompts desde cero","Contratar un prompt manager dedicado"],"correcta":1,"explicacion":"Sin saber qué tienes, no puedes organizar lo que tienes. El inventario revela duplicados, prompts huérfanos, y prompts críticos sin documentación — el mapa del terreno antes de construir el sistema."},
    {"id":"cert-58","bloque_origen":"B8","pregunta":"¿Por qué la especialización vertical multiplica el valor de un prompt engineer en el mercado?","opciones":["Porque hay menos competencia en nichos verticales únicamente","Porque combinar expertise técnico en prompting con conocimiento profundo de una industria permite resolver problemas de dominio específico que un generalista no puede — los clientes pagan premium por soluciones que entienden su negocio","Solo si la industria es tecnología o fintech","La especialización no aporta valor adicional sobre la experiencia técnica"],"correcta":1,"explicacion":"Un cliente de una aseguradora no busca 'alguien bueno con prompts' — busca alguien que entienda el proceso de suscripción, las regulaciones del sector, y los casos edge específicos del negocio. Ese combo es escaso y valioso."},
    {"id":"cert-59","bloque_origen":"Integración","pregunta":"Un sistema de análisis de contratos legales produce alucinaciones ocasionalmente. ¿Cuál es la combinación de técnicas más efectiva para resolver esto?","opciones":["Usar un modelo más grande que alucine menos","RAG (anclar respuestas al documento específico) + citación forzada (el modelo debe citar la cláusula específica para cada afirmación) + instrucción explícita de admitir incertidumbre cuando la información no está en el documento","Solo aumentar el budget_tokens de Extended Thinking","Agregar más ejemplos few-shot del formato esperado"],"correcta":1,"explicacion":"La combinación ataca las alucinaciones desde múltiples ángulos: RAG elimina la dependencia de la memoria del modelo; la citación forzada hace las alucinaciones detectables; la instrucción de admitir incertidumbre previene que el modelo invente cuando no sabe."},
    {"id":"cert-60","bloque_origen":"Integración","pregunta":"¿Cuál es el principio fundamental que subyace a todas las técnicas de prompt engineering aprendidas en el módulo M4?","opciones":["Usar el mayor número de tokens posible para dar más contexto","Comunicar con precisión y claridad qué se quiere, por qué, para quién es, en qué formato, y cómo verificar que está bien hecho — reduciendo la ambigüedad en cada dimensión de la instrucción","Siempre combinar el mayor número de técnicas posible","Usar los prompts que funcionaron para otros y adaptarlos"],"correcta":1,"explicacion":"Todas las técnicas del módulo — zero-shot, few-shot, CoT, XML tags, RAG, Extended Thinking, meta-prompting — son variaciones del mismo principio fundamental: reducir la ambigüedad en la comunicación entre humano y modelo. Quien entiende el principio puede adaptar cualquier técnica futura; quien solo memorizó las técnicas quedará obsoleto con cada nueva versión."}
  ]
};

fs.writeFileSync('src/content/m4-completo.json', JSON.stringify(data, null, 2), 'utf8');
const totalLecciones = data.bloques.reduce((s, b) => s + b.lecciones.length, 0);
const totalPreguntas = data.certificacion_final.preguntas.length;
const totalFases = data.proyecto_final.fases.length;
console.log('Proyecto final agregado. Fases:', totalFases);
console.log('Certificacion agregada. Preguntas:', totalPreguntas);
console.log('Total lecciones en bloques:', totalLecciones);
console.log('Archivo final listo.');
