const fs = require('fs'), path = require('path')
const file = path.join(__dirname, '../src/content/m1/index.json')
const data = JSON.parse(fs.readFileSync(file, 'utf8'))
const b1 = data.bloques[1]

function q(pregunta, opciones, correcta, explicacion_profunda, concepto_reforzado) {
  return { pregunta, opciones, correcta, explicacion_profunda, concepto_reforzado }
}

const nuevas = {
  'l5': {
    id: "m1-b1-l5", titulo: "IA estrecha vs IA general vs superinteligencia", bloque: 1,
    tipo: "leccion", duracion_min: 20, xp: 50,
    contenido: {
      teoria: {
        explicacion: `La distinción entre IA Estrecha (ANI), IA General (AGI) y Superinteligencia (ASI) no es solo filosófica — define el horizonte de lo que las herramientas de hoy pueden y no pueden hacer, y por qué los debates sobre "riesgo existencial de IA" y "IA que ya está aquí" no se contradicen.

IA Estrecha (Artificial Narrow Intelligence) es lo que existe hoy y es todo lo que existe hoy. Un modelo de ANI es extraordinariamente bueno en un dominio específico o conjunto limitado de dominios, pero carece de las capacidades de transferencia y adaptación que los humanos consideran "inteligencia general". GPT-4, Claude Sonnet, Gemini Ultra — todos son ANI. Son mejores que cualquier humano en generar texto, resumir documentos y escribir código en lenguajes específicos, pero si les pides hacer algo físico en el mundo real sin herramientas adicionales, no pueden. Son contexto-dependientes: necesitan que les des información que "fuera de la pantalla" asumirías implícita.

Un ejemplo revelador: Claude puede escribir código perfecto para calcular la ruta más corta entre dos ciudades usando algoritmos de grafos, pero no puede mirarte a los ojos durante una negociación y detectar que estás nervioso. Un humano promedio puede hacer ambas cosas (probablemente peor en la programación, mucho mejor en la negociación). Eso es ANI.

IA General (Artificial General Intelligence) es el nivel donde un sistema IA puede aprender a hacer cualquier tarea cognitiva que un humano pueda hacer, con la misma flexibilidad y transferencia de conocimiento entre dominios. Esto no existe todavía. El debate en la comunidad investigadora está en si GPT-5 o Claude 4 estarán "cerca" de AGI o si hay saltos cualitativos que aún no sabemos cómo lograr. La mayoría de investigadores serios piensan que AGI está entre 5 y 20 años. Algunos (Yann LeCun, entre otros) argumentan que los LLMs actuales no son la arquitectura que llevará a AGI.

Superinteligencia (ASI) es un sistema IA que supera a los humanos en virtualmente todas las dimensiones cognitivas y puede mejorar su propio diseño. Este es el nivel sobre el que hablan los teóricos de riesgo existencial como Nick Bostrom. ASI no existe, no está cerca, y hay desacuerdo genuino sobre si es inevitable, posible, o un escenario de ciencia ficción.

Para tu trabajo como AI Engineer en 2026: todo lo que construirás usa ANI. Entender sus limitaciones (falta de memoria persistente sin implementación explícita, falta de acceso al mundo físico, alucinaciones, dependencia del contexto) te permite diseñar sistemas más robustos. No esperes AGI para empezar — la ANI actual ya es suficientemente poderosa para resolver el 80% de los problemas de negocio de cualquier empresa.`,
        analogia: "ANI es como un gran maestro de ajedrez que solo sabe jugar ajedrez: imbatible en ese dominio específico, pero no sabe conducir. AGI sería alguien que puede aprender cualquier juego de mesa en una tarde y también conducir. ASI sería alguien que inventa juegos que los humanos no podrían imaginar.",
        ejemplo_malo: "Pensar que porque Claude puede escribir código en 10 lenguajes, 'pronto' podrá diseñar el plan de negocio de tu startup sin supervisión — eso confunde capacidad lingüística con razonamiento estratégico general.",
        ejemplo_bueno: "Usar Claude específicamente para las tareas en las que los LLMs son mejores que los humanos (síntesis rápida, generación de borradores, análisis de texto a escala) y reservar el juicio estratégico, la lectura de contexto político y las relaciones interpersonales para humanos.",
        por_que_importa: "Entender que estamos en la era de ANI evita dos errores costosos: subestimar lo que la IA actual puede hacer (y perder ventaja competitiva) y sobreestimar sus capacidades (y construir sistemas que fallarán en producción).",
        tip_profesional: "Cuando un cliente te pregunta si la IA 'va a pensar por sí misma', explica ANI vs AGI en 30 segundos: 'Lo que existe hoy es extremadamente bueno en tareas específicas pero no tiene iniciativa propia ni juicio general. Para que haga algo, tú defines exactamente qué.'"
      },
      verificacion: [
        q("¿Cuál es la principal diferencia entre ANI y AGI?", ["ANI es más costosa", "ANI está optimizada para dominios específicos mientras AGI podría transferir conocimiento y aprender cualquier tarea cognitiva humana", "AGI ya existe en algunos laboratorios", "ANI requiere más datos"], 1, "La diferencia fundamental es la transferencia de conocimiento entre dominios y la flexibilidad de aprendizaje. ANI (todo lo que existe hoy) es extraordinariamente buena en su dominio de entrenamiento pero no puede adaptarse genuinamente a dominios completamente nuevos sin reentrenamiento. AGI hipotéticamente tendría la misma flexibilidad cognitiva que un humano — aprender golf después de aprender tenis, o aprender derecho después de aprender medicina, transfiriendo conocimiento estructural.", "ANI vs AGI"),
        q("¿Qué significa que un modelo como Claude sea 'context-dependent'?", ["Que solo funciona en inglés", "Que necesita que el usuario provea la información contextual que un humano asumiría implícita fuera de la conversación", "Que necesita más memoria RAM", "Que es más lento"], 1, "La dependencia del contexto es una limitación clave de los LLMs actuales. Un humano en una reunión tiene acceso a señales no verbales, historia de la relación, conocimiento implícito del sector, y contexto de la conversación anterior. Un LLM solo tiene lo que está en su ventana de contexto. Si no le dices que eres CTO de una startup de 10 personas en Colombia, no lo puede inferir y puede darte respuestas optimizadas para un escenario completamente diferente.", "Limitaciones de contexto en LLMs"),
        q("¿Cuál es el consenso más extendido entre investigadores sobre el timeline para AGI?", ["AGI ya existe", "Entre 5 y 20 años, con gran incertidumbre", "Nunca será posible", "En exactamente 2030"], 1, "La honestidad intelectual sobre AGI requiere reconocer la incertidumbre. Las predicciones van desde 'ya casi' (Altman, Demis Hassabis) hasta 'en décadas' (LeCun, Turing Award winners) hasta 'nunca con arquitecturas actuales'. Lo que podemos decir con confianza: no existe hoy, el debate es genuino entre los mejores investigadores del mundo, y para decisiones de negocio en 2026, trabajamos con ANI.", "Timeline de AGI"),
        q("Para un AI Engineer práctico en 2026, ¿cuál de estas consideraciones sobre ANI es más relevante?", ["Que ANI es inferior a AGI", "Que ANI tiene limitaciones específicas (alucinaciones, dependencia del contexto, sin memoria persistente) que deben diseñarse explícitamente en los sistemas", "Que ANI va a desaparecer pronto", "Que ANI no puede hacer nada útil"], 1, "Conocer las limitaciones específicas de ANI es crítico para diseñar sistemas robustos. Las alucinaciones requieren verificación humana o sistemas de validación. La falta de memoria persistente requiere implementar sistemas de memoria explícita (bases de datos, RAG). La dependencia del contexto requiere diseñar prompts con toda la información relevante. Cada limitación tiene una solución de ingeniería — pero primero debes conocer la limitación.", "Diseño de sistemas con ANI"),
        q("¿Por qué Yann LeCun y otros investigadores argumentan que los LLMs podrían no ser la arquitectura que lleve a AGI?", ["Porque los LLMs son demasiado costosos", "Porque los LLMs aprenden patrones estadísticos de texto sin modelos del mundo que permitan razonamiento causal y planificación a largo plazo", "Porque son demasiado lentos", "Porque no pueden procesar imágenes"], 1, "El argumento de LeCun y otros es que la inteligencia general requiere modelos del mundo — representaciones causales de cómo las acciones producen efectos — no solo patrones estadísticos de texto. Un LLM puede decirte 'si empujas una pelota en una pendiente, rueda hacia abajo' porque lo leyó millones de veces, pero no tiene el modelo físico que le permitiría razonar sobre situaciones completamente nuevas. Esta limitación arquitectural podría requerir enfoques complementarios o alternativos.", "Limitaciones arquitecturales de LLMs")
      ],
      practica: {
        tipo: "caso_real",
        contexto: "Un cliente de manufactura te pregunta: '¿Podemos usar IA para que el sistema decida automáticamente si parar la línea de producción cuando detecte anomalías, sin supervisión humana?' La línea produce componentes médicos críticos.",
        instruccion: "Responde usando tu comprensión de ANI vs AGI para explicar qué puede y no puede hacer la IA actual en este contexto, y qué nivel de autonomía es recomendable.",
        input_malo: "Sí, la IA ya puede tomar decisiones autónomas perfectamente. Implementemos un sistema completamente automatizado.",
        pista: "Piensa en qué tipos de anomalías puede detectar ANI (patrones que ya vio en datos de entrenamiento) vs cuáles no puede (anomalías genuinamente nuevas). ¿Qué pasa si el sistema falla en un componente médico?",
        solucion: "La ANI actual puede detectar anomalías conocidas con alta precisión — si hemos entrenado el modelo con ejemplos de los tipos de defectos que queremos detectar, puede hacerlo mejor que un humano en velocidad y consistencia. Sin embargo, recomendaría un sistema de autonomía parcial para componentes médicos: la IA detecta y alerta con alta confianza, pero la decisión de parar la línea permanece con un operario humano por dos razones. Primera: ANI no puede razonar sobre anomalías genuinamente nuevas que no vio en entrenamiento — puede generar falsos negativos peligrosos. Segunda: en dispositivos médicos críticos, la responsabilidad legal requiere supervisión humana documentada. Diseño propuesto: IA con umbral de alerta al 85% de confianza → operario revisa → aprueba parada. Esto captura el 90% del valor (velocidad de detección) mientras mantiene el juicio humano donde el riesgo es crítico.",
        criterios_de_exito: [
          "Distingue claramente qué puede hacer ANI (detección de patrones conocidos) vs qué no puede (generalización a anomalías desconocidas)",
          "Justifica la necesidad de supervisión humana con argumentos técnicos Y regulatorios",
          "Propone un diseño de sistema concreto que maximice valor dentro de las limitaciones reales"
        ]
      },
      conexion: { siguiente_concepto: "IA simbólica vs conexionista", por_que_importa_despues: "Entender las dos filosofías fundamentales de la IA te da contexto para entender por qué los LLMs funcionan diferente a los sistemas expertos y cuándo usar cada enfoque." }
    }
  },
  'l6': {
    id: "m1-b1-l6", titulo: "IA simbólica vs conexionista: dos filosofías enfrentadas", bloque: 1,
    tipo: "leccion", duracion_min: 20, xp: 50,
    contenido: {
      teoria: {
        explicacion: `La historia de la IA es fundamentalmente la historia de dos enfoques filosóficos opuestos sobre qué es la inteligencia y cómo replicarla. Entender esta división te ayuda a entender por qué los LLMs modernos son revolucionarios, pero también por qué tienen limitaciones específicas que los sistemas simbólicos no tienen.

IA Simbólica (también llamada GOFAI — Good Old-Fashioned AI): La idea es que la inteligencia se puede representar completamente como manipulación de símbolos con reglas explícitas. Si defines todas las reglas del conocimiento humano de forma lógica, el sistema puede razonar. Los sistemas expertos de los años 80 eran IA simbólica: un experto médico pasaba meses codificando reglas del tipo "SI el paciente tiene fiebre > 38.5° Y tos seca ENTONCES considerar influenza". Prolog, los sistemas de lógica de primer orden, y los sistemas de razonamiento formal son IA simbólica. Sus ventajas: son interpretables (puedes trazar exactamente qué regla llevó a qué conclusión), son verificables formalmente, y son correctos dentro de su dominio de reglas. Sus desventajas: necesitan que humanos expertos codifiquen explícitamente todo el conocimiento, no escalan a dominios complejos y ambiguos, son frágiles ante variaciones no anticipadas.

IA Conexionista: La idea es que la inteligencia emerge de redes de nodos simples (neuronas artificiales) que aprenden patrones de datos sin que nadie les programe las reglas explícitamente. Las redes neuronales, el deep learning, y los LLMs son IA conexionista. En lugar de que un experto codifique "esto es un gato", la red neuronal ve millones de imágenes de gatos y aprende a reconocer los patrones visuales que constituyen un gato. Sus ventajas: aprende de datos masivos sin intervención humana por cada regla, generaliza a variaciones no vistas, puede manejar dominios donde las reglas son difíciles de articular (lenguaje natural, visión). Sus desventajas: es una caja negra (difícil saber por qué tomó una decisión específica), puede alucinaciones (aprendió un patrón incorrecto del ruido en los datos), necesita enormes cantidades de datos para entrenarse.

La síntesis actual — Sistemas Neuro-Simbólicos: El campo está evolucionando hacia sistemas que combinan ambos enfoques. Anthropic, por ejemplo, usa Constitutional AI que incorpora principios explícitos (simbólicos) para guiar el entrenamiento del modelo conexionista. Los sistemas de RAG (Retrieval Augmented Generation) combinan recuperación simbólica (búsqueda en base de datos estructurada) con generación conexionista (LLM).

Para ti como AI Engineer: cuando construyas sistemas con LLMs, probablemente necesites añadir capas simbólicas para compensar las limitaciones conexionistas. ¿Necesitas que el sistema siempre siga ciertas reglas de negocio? Añade validación simbólica. ¿Necesitas explicabilidad? Añade logging de razonamiento. ¿El LLM alucina en un dominio específico? Añade una base de conocimiento estructurada con RAG.`,
        analogia: "IA simbólica es como un abogado que tiene un libro de leyes y las aplica lógicamente. IA conexionista es como un juez experimentado que ha visto miles de casos y desarrolló intuición sobre qué es justo — pero no siempre puede explicar exactamente por qué tomó una decisión.",
        ejemplo_malo: "Usar solo un LLM (conexionista) para un sistema de compliance bancario donde cada decisión debe ser auditable y seguir regulaciones explícitas — el LLM puede dar respuestas correctas pero no documentables.",
        ejemplo_bueno: "Sistema híbrido: LLM para entender la consulta del cliente en lenguaje natural + motor de reglas simbólico para verificar contra regulaciones explícitas + LLM para generar la respuesta final. Lo mejor de ambos mundos.",
        por_que_importa: "Cuando diseñes sistemas de IA en producción, inevitablemente enfrentarás casos donde el LLM solo no es suficiente. Conocer el paradigma simbólico te da las herramientas para diseñar el componente que falta.",
        tip_profesional: "Pregúntate en cada sistema de IA que diseñes: ¿Hay reglas de negocio absolutas que el sistema NUNCA debe violar? Esas van en código simbólico, no en el prompt del LLM. Los prompts son conexionistas — probabilísticos. El código es simbólico — determinístico."
      },
      verificacion: [
        q("¿Cuál es la ventaja principal de los sistemas simbólicos sobre los conexionistas?", ["Son más rápidos", "Son interpretables: puedes trazar exactamente qué regla llevó a cada decisión", "Necesitan menos datos", "Son más fáciles de entrenar"], 1, "La interpretabilidad es la ventaja crítica de los sistemas simbólicos. En dominios donde la explicabilidad es legal o éticamente requerida — medicina, derecho, finanzas reguladas — los sistemas simbólicos tienen una ventaja que los LLMs no pueden igualar fácilmente. Puedes mostrar exactamente qué regla llevó a qué conclusión, lo que facilita la auditoría, la corrección de errores y la responsabilidad.", "Interpretabilidad en IA simbólica"),
        q("¿Por qué los sistemas expertos de los años 80 (IA simbólica) fallaron como solución general?", ["Eran demasiado caros", "Requerían que expertos humanos codificaran manualmente cada regla, lo que no escalaba a dominios complejos", "No tenían suficiente memoria", "No podían conectarse a internet"], 1, "El cuello de botella de los sistemas expertos era el 'knowledge engineering' — el proceso de extraer conocimiento de expertos humanos y codificarlo como reglas. Para cada nuevo dominio, necesitabas meses de trabajo de expertos. Además, el lenguaje natural y el mundo real son tan ambiguos y variados que ninguna lista finita de reglas puede capturarlos completamente. Cuando el sistema encontraba una variación no anticipada, fallaba sin gracefulidad.", "Limitaciones de IA simbólica"),
        q("¿Qué son los sistemas Neuro-Simbólicos?", ["Una nueva empresa de IA", "Sistemas que combinan redes neuronales conexionistas con componentes simbólicos para obtener ventajas de ambos enfoques", "Un tipo de robot", "Software médico"], 1, "Los sistemas neuro-simbólicos representan el estado del arte actual del campo. Constitutional AI de Anthropic usa principios explícitos (simbólicos) para guiar el entrenamiento conexionista. RAG combina recuperación estructurada (simbólica) con generación de lenguaje (conexionista). AlphaGo combinó redes neuronales profundas con Monte Carlo Tree Search (búsqueda simbólica). La tendencia es que las soluciones más robustas usan ambos paradigmas.", "Sistemas neuro-simbólicos"),
        q("¿Cuándo debería un AI Engineer preferir añadir una capa simbólica en lugar de depender solo del LLM?", ["Siempre", "Cuando hay reglas de negocio absolutas que deben cumplirse determinísticamente, o cuando la auditabilidad es legalmente requerida", "Nunca, los LLMs pueden hacer todo", "Solo en sistemas médicos"], 1, "Las capas simbólicas son esenciales cuando: (1) el sistema tiene reglas de negocio que no pueden violarse probabilísticamente (un LLM puede 'olvidar' una regla con baja probabilidad, y eso es inaceptable en muchos contextos), (2) la auditoría requiere trazabilidad exacta, (3) el dominio tiene reglas formales bien definidas. Ejemplo: un sistema de préstamos puede usar LLM para entender la solicitud, pero un motor de reglas determinístico para verificar criterios de elegibilidad legales.", "Cuándo usar IA simbólica vs conexionista"),
        q("¿Por qué un LLM como Claude se considera IA conexionista?", ["Porque usa conexiones de internet", "Porque es una red neuronal que aprendió patrones estadísticos de grandes cantidades de datos sin reglas explícitas programadas", "Porque conecta diferentes tipos de datos", "Porque trabaja con múltiples usuarios simultáneamente"], 1, "Claude, como todos los LLMs modernos, es una red neuronal transformer de miles de millones de parámetros que fue entrenada prediciendo el siguiente token en enormes corpus de texto. Nadie programó explícitamente que 'sustantivo + verbo = oración válida' — el modelo aprendió la gramática, el contexto, el razonamiento y el conocimiento del mundo a través de la exposición masiva a datos. Esto lo hace poderoso (generaliza bien) pero también lo hace una caja negra difícil de auditar.", "LLMs como IA conexionista")
      ],
      practica: {
        tipo: "caso_real",
        contexto: "Estás diseñando un sistema de IA para una aseguradora que debe: (1) entender consultas de clientes en lenguaje natural, (2) verificar elegibilidad según pólizas específicas, (3) generar respuestas claras. Tienes $500/mes de presupuesto de API.",
        instruccion: "Diseña la arquitectura del sistema especificando qué partes serían conexionistas (LLM) y qué partes serían simbólicas (reglas, bases de datos), y por qué.",
        input_malo: "Usaría solo Claude con un prompt muy detallado que incluya todas las reglas de las pólizas.",
        pista: "Las pólizas tienen condiciones exactas (si el cliente tiene X cobertura y el evento Y ocurrió, entonces Z está cubierto). ¿Esas condiciones exactas deben ser probabilísticas o determinísticas?",
        solucion: "Arquitectura en 3 capas: Capa 1 (Conexionista/LLM): Claude entiende la consulta del cliente en lenguaje natural, extrae entidades clave (tipo de evento, fecha, número de póliza) y las convierte a parámetros estructurados. Esta parte sí es adecuada para LLM porque el lenguaje natural es el dominio donde brilla. Capa 2 (Simbólica/Motor de reglas): Un sistema de reglas determinístico verifica las condiciones exactas de la póliza contra los parámetros extraídos. Esta parte NO debe ser LLM porque las decisiones de cobertura deben ser auditables y 100% consistentes — si la condición X se cumple, siempre se cubre, sin probabilidad. Capa 3 (Conexionista/LLM): Claude genera la respuesta final al cliente de forma clara y empática, explicando la decisión de la capa 2 en lenguaje humano. Beneficios: auditabilidad (la capa 2 es trazable), experiencia de usuario (las capas 1 y 3 son conversacionales), cumplimiento regulatorio (las decisiones son determinísticas y documentables).",
        criterios_de_exito: [
          "Identifica correctamente qué partes del sistema deben ser determinísticas (simbólicas) y cuáles probabilísticas (conexionistas)",
          "Justifica el uso de cada paradigma basado en los requisitos específicos",
          "Propone una arquitectura de 3 capas o similar que combine ambos enfoques"
        ]
      },
      conexion: { siguiente_concepto: "Modelos discriminativos vs generativos", por_que_importa_despues: "Esta distinción técnica explica por qué los mismos datos de entrenamiento pueden producir modelos con propósitos completamente diferentes." }
    }
  },
  'l7': {
    id: "m1-b1-l7", titulo: "Modelos discriminativos vs generativos: qué diferencia hay", bloque: 1,
    tipo: "leccion", duracion_min: 20, xp: 50,
    contenido: {
      teoria: {
        explicacion: `Cuando la gente dice "IA generativa" están usando una distinción técnica importante que define dos familias completamente diferentes de modelos de IA, con propósitos, arquitecturas y casos de uso distintos. Entender esta diferencia te ayuda a elegir el tipo de modelo correcto para cada problema.

Modelos Discriminativos: Aprenden a distinguir entre categorías. Dado un input, responden: ¿A qué categoría pertenece esto? El clásico ejemplo es un clasificador de spam. Se entrena con miles de emails etiquetados como spam o no-spam, y aprende los patrones que distinguen una categoría de la otra. Técnicamente, aprenden P(categoría | input) — la probabilidad de que un input pertenezca a cada categoría dado el input. Modelos discriminativos comunes: clasificadores de sentimiento, detección de objetos en imágenes, clasificación de documentos, detección de fraude, diagnóstico médico binario. La pregunta que responden es SIEMPRE una variación de "¿qué es esto?" o "¿a qué grupo pertenece?"

Modelos Generativos: Aprenden la distribución completa de los datos. No solo saben distinguir categorías — saben generar nuevos ejemplos que "pertenecen" a esa distribución. Técnicamente, aprenden P(input) — la probabilidad de que cualquier punto de datos sea parte de la distribución aprendida. Esto les permite generar texto nuevo, imágenes nuevas, audio nuevo. GPT-4, Claude, Stable Diffusion, DALL-E, Midjourney — todos son modelos generativos. La pregunta que responden es "¿cómo sería un nuevo ejemplo de esto?"

Por qué la distinción importa en la práctica: Si quieres clasificar si un email es phishing o legítimo, un modelo discriminativo entrenado específicamente para esa tarea será más eficiente y preciso que pedirle a Claude (un modelo generativo) que clasifique. Si quieres generar borradores de respuesta a emails de clientes, un modelo generativo como Claude es la herramienta correcta.

Los LLMs modernos son generativos por naturaleza: predicen la distribución de probabilidad sobre el siguiente token. Pero pueden usarse de forma discriminativa. Si le preguntas a Claude "¿Este email es spam? Responde solo Sí o No", estás forzando al modelo generativo a comportarse como discriminativo. Funciona, pero generalmente hay clasificadores especializados que son más precisos y económicos para esa tarea específica.

La era de la IA Generativa (GenAI): El término "IA generativa" se popularizó en 2022-2023 para referirse específicamente a los modelos que generan contenido nuevo de alta calidad (texto, imagen, audio, video, código). No es un término técnico preciso — es un término de mercado que captura la característica más visible de los modelos actuales. Cuando escuchas "herramientas de GenAI", piensan en modelos que crean, no que clasifican.`,
        analogia: "Un modelo discriminativo es como un sommelier que puede identificar si un vino es de Borgoña o Rioja. Un modelo generativo es como un viticultor que puede crear un nuevo vino con las características de Borgoña. Ambos conocen el vino — pero hacen cosas diferentes con ese conocimiento.",
        ejemplo_malo: "Usar Claude (modelo generativo) para clasificar miles de documentos por categoría cuando hay clasificadores discriminativos específicos disponibles — innecesariamente caro y potencialmente menos preciso.",
        ejemplo_bueno: "Usar un clasificador discriminativo para filtrar primero (spam/no-spam) y luego Claude (generativo) para generar la respuesta personalizada al email no-spam — cada modelo donde tiene ventaja.",
        por_que_importa: "En arquitecturas de sistemas de IA reales, típicamente combinas ambos tipos. Entender la diferencia te permite elegir el modelo correcto para cada componente y evitar usar un mazo cuando necesitas un bisturí.",
        tip_profesional: "Regla práctica: ¿El problema es 'categorizar' o 'crear'? Si categorizar, considera un clasificador discriminativo especializado. Si crear (texto, código, imágenes, análisis), usa un modelo generativo. Muchos problemas tienen ambas fases."
      },
      verificacion: [
        q("¿Cuál es la diferencia fundamental entre un modelo discriminativo y uno generativo?", ["Los generativos son más modernos", "Los discriminativos aprenden a clasificar entre categorías; los generativos aprenden la distribución completa de datos y pueden crear nuevos ejemplos", "Los discriminativos son más baratos", "Los generativos solo funcionan con texto"], 1, "La diferencia es conceptual y matemática. Un clasificador discriminativo aprende P(y|x) — la probabilidad de la etiqueta dado el input. Solo puede decirte en qué categoría cae algo. Un modelo generativo aprende P(x) — la distribución completa de los datos, lo que le permite generar nuevos puntos de datos realistas. Esta capacidad de generación es lo que hace posibles los LLMs, DALL-E, Stable Diffusion y todos los modelos de 'IA generativa'.", "Discriminativo vs Generativo"),
        q("¿Por qué Claude (modelo generativo) puede usarse para clasificar, pero hay casos en que un clasificador específico es mejor?", ["Claude no puede clasificar", "Los clasificadores discriminativos entrenados específicamente para una tarea son más precisos y económicos en ese dominio que un modelo generativo de propósito general", "Claude solo funciona en inglés", "Los clasificadores son más modernos"], 1, "Usar Claude para clasificar spam funciona, pero un clasificador BERT fine-tuned específicamente para spam detectará patrones más sutiles con mayor precisión y menor costo por inferencia. La razón es que Claude está optimizado para generación de texto de calidad general, mientras que un clasificador específico dedicó toda su capacidad de aprendizaje a esa tarea puntual. En producción, la elección correcta puede significar 10x menos costo y 15% más precisión.", "Elección correcta de modelo"),
        q("¿Qué tienen en común GPT-4, Claude y Stable Diffusion que los hace a todos 'modelos generativos'?", ["Todos son de la misma empresa", "Todos aprenden distribuciones de datos y pueden generar nuevos ejemplos (texto o imágenes) que parecen provenir de la misma distribución", "Todos son gratuitos", "Todos usan la misma arquitectura"], 1, "Aunque GPT-4 y Claude generan texto y Stable Diffusion genera imágenes, los tres son generativos porque aprenden la distribución estadística de sus datos de entrenamiento y pueden muestrear de esa distribución para generar nuevos ejemplos. La diferencia es el tipo de datos (texto vs imágenes) y la arquitectura específica (transformers vs diffusion models), pero el concepto subyacente de 'aprender para generar' es el mismo.", "Modelos generativos en diferentes dominios"),
        q("¿Cuándo es apropiado forzar a un modelo generativo como Claude a comportarse como clasificador (ej: 'responde solo Sí o No')?", ["Nunca, los modelos generativos no pueden clasificar", "Cuando la clasificación no es el core del sistema o cuando ya tienes Claude integrado y el volumen no justifica un clasificador separado", "Siempre, es más sencillo", "Solo para texto en español"], 1, "Forzar a Claude a clasificar con outputs binarios funciona y es razonable en contextos como: prototipos, sistemas de baja escala, cuando la calidad de clasificación no es crítica, o cuando el LLM ya está integrado y añadir otro modelo añade complejidad innecesaria. En producción a escala donde la clasificación es el bottleneck o donde la precisión es crítica, vale la pena el modelo especializado.", "Uso pragmático de modelos generativos como clasificadores"),
        q("¿Qué es técnicamente lo que aprende un modelo discriminativo expresado como P(y|x)?", ["La probabilidad de los datos de entrenamiento", "La probabilidad de la etiqueta y dado el input x — es decir, qué categoría corresponde a cada input", "La probabilidad de generar texto nuevo", "La velocidad de procesamiento"], 1, "P(y|x) es la notación matemática para 'probabilidad condicional de y dado x'. En un clasificador de spam, y es la categoría (spam/no-spam) y x es el email. El modelo aprende a estimar qué tan probable es cada categoría para cada input posible. Esto contrasta con P(x) que aprende un modelo generativo — la probabilidad de que cualquier punto de datos sea parte de la distribución aprendida.", "Probabilidad condicional en modelos discriminativos")
      ],
      practica: {
        tipo: "caso_real",
        contexto: "Una empresa de e-commerce quiere implementar IA en su proceso de atención al cliente. Tienen dos necesidades: (1) clasificar automáticamente los tickets de soporte por categoría (devolución, problema técnico, queja, información), y (2) generar respuestas personalizadas para cada ticket según su categoría.",
        instruccion: "Diseña la solución técnica especificando qué tipo de modelo usarías para cada necesidad y por qué.",
        input_malo: "Usaría Claude para todo: le pido que clasifique el ticket y luego que genere la respuesta.",
        pista: "¿Cuántos tickets procesan por día? Si son miles, ¿importa el costo por clasificación? ¿Qué precisión necesita la clasificación para que el sistema funcione bien?",
        solucion: "Solución en dos fases: Fase 1 — Clasificación (Modelo Discriminativo): Usar un clasificador BERT fine-tuned en los tickets históricos de la empresa (probablemente tienen miles ya etiquetados). Costo: inferencia de clasificador es 20-50x más barato que Claude. Precisión: 92-95% para 4 categorías bien definidas. Velocidad: ms por clasificación vs segundos con LLM. Fase 2 — Generación de respuesta (Modelo Generativo / Claude): Una vez clasificado el ticket, pasar a Claude con el contexto: tipo de ticket, historial del cliente, políticas de la empresa, y pedir respuesta personalizada. Aquí sí vale el costo del LLM porque la respuesta de calidad es el valor diferenciador. Resultado: 95% de tickets clasificados automáticamente + respuestas personalizadas de alta calidad + costo optimizado (clasificación barata + generación donde importa).",
        criterios_de_exito: [
          "Identifica correctamente que la clasificación es tarea discriminativa y la generación de respuesta es tarea generativa",
          "Justifica la elección de cada tipo de modelo con argumentos de precisión, costo y escala",
          "Diseña un flujo de dos fases que combina ambos tipos optimamente"
        ]
      },
      conexion: { siguiente_concepto: "Multimodalidad: texto, imagen, audio, video y código unidos", por_que_importa_despues: "La multimodalidad representa la convergencia de todos los tipos de modelos en sistemas unificados — el siguiente paso después de entender los tipos individuales." }
    }
  },
  'l8': {
    id: "m1-b1-l8", titulo: "Multimodalidad: texto, imagen, audio, video y código unidos", bloque: 1,
    tipo: "leccion", duracion_min: 20, xp: 50,
    contenido: {
      teoria: {
        explicacion: `La multimodalidad es el desarrollo más transformador de los últimos 2 años en IA práctica. Un modelo multimodal puede entender y generar múltiples tipos de información — texto, imágenes, audio, video, código — de forma integrada, no como sistemas separados conectados, sino como un único sistema que puede razonar sobre todos estos tipos de datos simultáneamente.

El camino hacia la multimodalidad: Hasta 2021, los mejores modelos de IA eran uni-modales. GPT-3 solo procesaba texto. DALL-E 1 solo generaba imágenes. Whisper (2022) transcribía audio. Cada modelo era excelente en su dominio, pero no había integración real. El salto llegó con GPT-4V (2023), Claude 3 (2024) y Gemini (2023): modelos que podían recibir texto e imágenes simultáneamente y razonar sobre ambos de forma integrada. El siguiente salto: GPT-4o (2024) y Gemini 1.5 Ultra pueden procesar texto, imágenes, audio y video en tiempo real. Claude 3.5 puede razonar sobre imágenes complejas incluyendo gráficas, screenshots y diagramas.

Por qué la multimodalidad es diferente a "conectar sistemas separados": Si conectas OCR + LLM + sistema de imágenes, cada pieza ve una representación diferente del mismo dato y pierde contexto al pasar entre sistemas. Un modelo multimodal nativo tiene representaciones internas que integran toda la información desde el principio. Puede razonar: "esta gráfica muestra una tendencia que contradice lo que dice el texto en el párrafo anterior" — algo que un sistema conectado no puede hacer sin pipes complejos y pérdida de información.

Casos de uso concretos que cambian procesos reales: Análisis de documentos médicos: Un modelo multimodal puede leer simultáneamente el texto del historial clínico y la imagen del scan, y razonar sobre ambos. Revisión de contratos con tablas: Entender texto legal y las tablas numéricas embebidas como un todo coherente. Debugging de interfaces: Tomar un screenshot del error en producción y el mensaje de error juntos. Análisis de videos de reuniones: Transcribir, entender el contexto visual, identificar quién habla cuándo. Arquitectura de software desde diagramas: Interpretar un diagrama de arquitectura y generar el código correspondiente.

Lo que viene: Modelos nativamente multimodales de audio y video en tiempo real (ya en beta en 2024-2025). La convergencia es hacia un único sistema que pueda manejar cualquier tipo de input y output de forma fluida. Esto no es ciencia ficción — es la dirección clara de todos los grandes laboratorios.

Limitaciones actuales importantes: Los modelos multimodales actuales siguen siendo mejores con texto que con imagen o audio. El razonamiento espacial en imágenes complejas todavía comete errores. El video a escala (> 30 minutos) todavía tiene limitaciones de contexto. La generación de video de alta calidad aún no está completamente integrada en los modelos de texto.`,
        analogia: "Un modelo uni-modal es como un especialista que solo habla un idioma. Puedes contratar un traductor para comunicarte, pero pierdes matices. Un modelo multimodal es como alguien que es nativo en todos los idiomas y puede razonar en todos simultáneamente sin pérdida de contexto.",
        ejemplo_malo: "Construir un sistema para analizar facturas: OCR extrae el texto → LLM analiza el texto → sistema separado valida las tablas numéricas → otro sistema verifica el logo de la empresa. Cuatro sistemas, tres puntos de fallo, pérdida de contexto entre cada paso.",
        ejemplo_bueno: "Enviar la imagen de la factura directamente a Claude o GPT-4o: 'Analiza esta factura, extrae los ítems, calcula el subtotal, verifica que los cálculos son correctos, e identifica cualquier anomalía.' Un solo paso, contexto completo, resultado en segundos.",
        por_que_importa: "La multimodalidad elimina categorías enteras de sistemas complejos y pipes de procesamiento que antes requerían múltiples herramientas especializadas. Para un AI Engineer, significa que puedes resolver problemas más complejos con menor complejidad de sistema.",
        tip_profesional: "Antes de construir un pipeline complejo de procesamiento de documentos, prueba siempre primero: ¿puede Claude o GPT-4o resolver esto directamente enviando el documento/imagen? En el 70% de los casos, la respuesta es sí y ahorras semanas de desarrollo."
      },
      verificacion: [
        q("¿Cuál es la diferencia fundamental entre un sistema multimodal 'conectado' y un modelo nativo multimodal?", ["Solo la velocidad", "Un sistema conectado pierde contexto al pasar entre modelos separados; un modelo nativo integra todos los tipos de datos en representaciones internas unificadas desde el inicio", "El costo", "La cantidad de modelos usados"], 1, "La integración nativa es cualitativamente diferente porque el modelo tiene representaciones internas que capturan la relación entre modalidades. Cuando Claude ve una gráfica junto a texto, no 'convierte la imagen a descripción y luego analiza el texto de la descripción' — razona sobre ambos como un todo coherente. Esto permite detectar contradicciones entre modalidades, algo imposible con sistemas separados sin pipes muy elaborados.", "Multimodalidad nativa vs conectada"),
        q("¿Qué hito del 2023-2024 marcó el inicio de la era verdaderamente multimodal?", ["El lanzamiento de Stable Diffusion", "GPT-4V, Claude 3 y Gemini — modelos que podían procesar texto e imágenes de forma integrada y razonar sobre ambos", "El primer smartphone con IA", "Whisper de OpenAI"], 1, "GPT-4V (Vision) fue el primer modelo ampliamente disponible que podía recibir imágenes junto con texto y razonar sobre ambos de forma integrada, no solo describir imágenes. Claude 3 y Gemini siguieron con capacidades similares o superiores. Esto fue un salto cualitativo porque permitió casos de uso completamente nuevos: análisis de documentos complejos, debugging visual, comprensión de diagramas.", "Hitos de la multimodalidad"),
        q("¿Cuál es un caso de uso donde la multimodalidad ofrece ventaja clara sobre un LLM de solo texto?", ["Traducción de idiomas", "Análisis de una factura con tablas y texto donde el modelo necesita razonar sobre la relación entre texto y números simultáneamente", "Generación de código", "Responder preguntas de historia"], 1, "Una factura tiene texto (descripción de ítems, condiciones de pago) y tablas numéricas (precios, cantidades, subtotales, IVA). Para verificar que los cálculos son correctos, necesitas razonar sobre la relación entre el texto y los números. Un LLM de solo texto vería la factura transcrita como texto plano y perdería la estructura visual de las tablas. Un modelo multimodal ve la imagen completa y puede razonar sobre la estructura, detectar errores de cálculo y anomalías.", "Casos de uso de multimodalidad"),
        q("¿Cuál de estas es una limitación real de los modelos multimodales actuales en 2026?", ["No pueden procesar texto", "El razonamiento espacial en imágenes complejas todavía comete errores, y el video a escala larga tiene limitaciones de contexto", "No pueden generar respuestas en español", "Solo funcionan con documentos PDF"], 1, "Los modelos multimodales actuales son excelentes con texto e imágenes simples, pero tienen limitaciones reales: el razonamiento espacial preciso (¿cuántos objetos hay en el cuadrante superior derecho?) todavía comete errores, especialmente en imágenes densas. El video de larga duración supera las ventanas de contexto actuales. La generación de video de alta calidad integrada con texto todavía está en desarrollo. Conocer estas limitaciones evita sobrediseñar sistemas que asumen capacidades que aún no existen robustamente.", "Limitaciones de multimodalidad actual"),
        q("¿Qué estrategia práctica recomienda el módulo antes de construir un pipeline complejo de procesamiento de documentos?", ["Siempre construir el pipeline completo desde el inicio", "Probar primero si Claude o GPT-4o pueden resolver el problema directamente enviando el documento o imagen — en el 70% de los casos funciona y ahorra semanas", "Usar siempre sistemas separados para mayor control", "Esperar a que la tecnología madure más"], 1, "La regla del 'multimodal primero' ahorra semanas de desarrollo en muchos casos. Antes de construir: OCR → parser → validador → LLM, prueba primero: envía la imagen directamente a un modelo multimodal. Si funciona con la calidad requerida, has ahorrado la complejidad de 3-4 sistemas. Si no funciona perfectamente, ahora tienes información específica sobre qué parte del pipeline necesitas optimizar.", "Estrategia práctica con modelos multimodales")
      ],
      practica: {
        tipo: "caso_real",
        contexto: "Una firma de contabilidad tiene 500 facturas de proveedores que llegan mensualmente en diferentes formatos (PDF escaneados, fotos de facturas en papel, PDFs digitales). Actualmente un contador junior pasa 3 días al mes extrayendo datos de estas facturas a una hoja de Excel para conciliación.",
        instruccion: "Diseña un sistema con IA multimodal que reduzca este proceso de 3 días a menos de 3 horas. Especifica qué modelo usarías, cómo lo integrarías con el sistema actual, y cuáles son los puntos que aún requerirían revisión humana.",
        input_malo: "Implementar OCR para extraer el texto y luego un LLM para procesar el texto extraído.",
        pista: "Las facturas tienen texto, tablas y a veces logos o marcas de agua. ¿Cuánto contexto se pierde al convertir primero a texto?",
        solucion: "Sistema de procesamiento multimodal: Paso 1 — Ingesta: Todas las facturas (PDF, imágenes) se envían directamente como imágenes a Claude claude-sonnet-4-6 con el prompt: 'Extrae en JSON: proveedor, RUT, fecha, número de factura, ítems con descripción y valor, subtotal, impuestos, total. Si algo es ilegible o parece incorrecto, márcalo con flag:true.' Paso 2 — Validación automática: Script en Python verifica que los totales calculados coincidan con el total declarado, que el RUT tenga formato válido, y que la fecha sea razonable. Flaggea cualquier discrepancia. Paso 3 — Exportación: Los registros sin flags se exportan automáticamente al Excel. Estimación de tiempo: 500 facturas a 15 segundos cada una = ~2 horas de procesamiento. Paso 4 — Revisión humana (30-60 min): El contador revisa solo las facturas flaggeadas (estimado 5-10% con algún problema). Resultado: De 3 días → 2-3 horas. Ventaja vs OCR+LLM: el modelo multimodal maneja la estructura visual de tablas, logos de verificación y formatos irregulares sin pipeline adicional.",
        criterios_de_exito: [
          "Propone usar un modelo multimodal nativo en lugar de OCR + LLM",
          "Diseña el sistema de flags/excepciones para mantener supervisión humana donde el sistema no está seguro",
          "Estima el tiempo realistically y distingue procesamiento automático de revisión humana"
        ]
      },
      conexion: { siguiente_concepto: "Agentes autónomos: la nueva frontera de la IA", por_que_importa_despues: "Los agentes son la capa que convierte modelos multimodales pasivos en sistemas que pueden tomar acciones en el mundo — el salto de herramienta a colaborador." }
    }
  },
  'l9': {
    id: "m1-b1-l9", titulo: "Agentes autónomos: la nueva frontera de la IA", bloque: 1,
    tipo: "leccion", duracion_min: 20, xp: 50,
    contenido: {
      teoria: {
        explicacion: `Hasta 2024, los LLMs eran fundamentalmente reactivos: respondían a preguntas. Los agentes autónomos representan el salto hacia sistemas que pueden planificar, tomar acciones en el mundo real, y completar objetivos de múltiples pasos sin supervisión humana en cada paso.

¿Qué es un agente de IA? Un agente es un sistema de IA que tiene: (1) Percepción — puede recibir inputs del entorno (texto, datos, resultados de herramientas), (2) Razonamiento — puede planificar una secuencia de pasos para lograr un objetivo, (3) Acción — puede ejecutar herramientas o tomar acciones con efectos reales, (4) Memoria — puede mantener contexto a través de múltiples pasos, y (5) Evaluación — puede verificar si sus acciones lograron el objetivo.

La diferencia entre LLM y agente: Pedirle a Claude "escribe un email de seguimiento para este cliente" es usar un LLM como herramienta. Darle a Claude "gestiona el seguimiento de todos los leads de esta semana: revisa el CRM, identifica quién necesita seguimiento, escribe emails personalizados, y programa los envíos" — eso es un agente. El agente usa herramientas (acceso al CRM, acceso al servicio de email, calendario) y completa el objetivo en múltiples pasos.

Frameworks de agentes actuales: Claude Computer Use (2024): Claude puede controlar directamente un navegador y computadora. Puede navegar sitios web, hacer clic, llenar formularios, tomar screenshots y razonar sobre lo que ve. LangChain Agents: Framework para construir agentes que pueden usar herramientas definidas por el desarrollador. AutoGen (Microsoft): Framework para sistemas multi-agente donde múltiples LLMs colaboran. CrewAI: Especializado en agentes con roles definidos que trabajan en equipo. Claude Code (2025): Agente especializado en desarrollo de software que puede editar archivos, correr tests y resolver bugs de forma autónoma.

Casos de uso reales en 2026: Investigación de mercado autónoma: El agente busca en múltiples fuentes, extrae datos, los compara y genera el reporte. Marketing automatizado: El agente monitorea menciones de marca, genera respuestas, las publica y reporta resultados. Desarrollo de software: El agente lee los requisitos, escribe el código, corre los tests, corrige los errores detectados, y hace el pull request. Soporte al cliente de nivel 1: El agente lee el ticket, consulta la base de conocimiento, verifica el estado en el sistema, y resuelve o escala con contexto completo.

Riesgos de los agentes y cómo mitigarlos: El poder de los agentes viene con riesgos nuevos. Un agente que puede tomar acciones reales puede cometer errores reales. Principios de diseño seguro: Human-in-the-loop para acciones de alto impacto (no automatices borrar datos o hacer pagos sin aprobación), scope limitado (dale al agente solo las herramientas que necesita), logging completo de todas las acciones, y rollback capability cuando sea posible.`,
        analogia: "La diferencia entre un LLM y un agente es como la diferencia entre un consultor que te da recomendaciones en una reunión y un gerente de proyectos que ejecuta el proyecto completo. Ambos son expertos — uno te dice qué hacer, el otro lo hace.",
        ejemplo_malo: "Crear un agente con acceso completo a todos los sistemas de la empresa (CRM, emails, bases de datos, APIs de pago) sin aprobación humana requerida para ninguna acción, esperando que el LLM 'tenga buen juicio'.",
        ejemplo_bueno: "Agente de seguimiento de leads con: acceso de lectura al CRM, capacidad de generar borradores de email, pero con aprobación humana requerida antes de cada envío — captura el valor de la automatización con supervisión donde importa.",
        por_que_importa: "Los agentes son donde la IA pasa de ser una herramienta de productividad personal a ser un colaborador que puede completar tareas completas de negocio. Quien sepa diseñar y desplegar agentes correctamente tendrá ventaja competitiva significativa en 2026-2027.",
        tip_profesional: "Para tu primer agente, elige una tarea completamente interna y reversible — donde un error no tenga consecuencias externas. Ejemplo perfecto: agente que genera borradores de contenido para redes sociales que tú revisas antes de publicar. Aprende el patrón con bajo riesgo."
      },
      verificacion: [
        q("¿Cuál es la diferencia fundamental entre usar un LLM como herramienta y un agente autónomo?", ["El costo", "Un LLM responde preguntas; un agente planifica y ejecuta secuencias de acciones con herramientas reales para lograr objetivos de múltiples pasos", "La velocidad de respuesta", "El lenguaje de programación usado"], 1, "La distinción clave es la agencia — la capacidad de actuar en el mundo, no solo de generar texto. Un agente tiene herramientas que producen efectos reales (enviar emails, modificar bases de datos, navegar la web), puede planificar secuencias de pasos, y puede auto-evaluar si sus acciones están logrando el objetivo. Esto lo convierte en un sistema que puede completar tareas completas, no solo responder preguntas.", "LLM vs Agente"),
        q("¿Cuáles son los 5 componentes que definen un agente de IA?", ["Velocidad, precisión, costo, memoria, escala", "Percepción, razonamiento, acción, memoria y evaluación", "Texto, imagen, audio, video, código", "Entrenamiento, fine-tuning, deployment, monitoring, retirement"], 1, "Los 5 componentes del framework de agentes (PRAME): Percepción (recibir inputs), Razonamiento (planificar pasos), Acción (ejecutar herramientas con efectos reales), Memoria (mantener contexto), Evaluación (verificar si el objetivo se logró). Un sistema que tiene los 5 puede ser considerado un agente. Si falta alguno, es una herramienta más limitada. Por ejemplo, sin memoria, no puede mantener el contexto de un proceso de múltiples días.", "Componentes de un agente de IA"),
        q("¿Cuál de estos ejemplos representa mejor un agente autónomo vs un LLM como herramienta?", ["'Resume este artículo' (agente) vs 'Investiga el mercado y genera un reporte de competidores' (herramienta)", "'Investiga el mercado y genera un reporte de competidores accediendo a múltiples fuentes' (agente) vs 'Resume este artículo' (herramienta)", "Ambos son igual de agénticos", "Ninguno es agéntico"], 1, "El primer ejemplo requiere planificación multi-paso, uso de herramientas externas (búsqueda web, bases de datos), y capacidad de sintetizar información de múltiples fuentes autónomamente. El segundo ejemplo ('resume este artículo') es una tarea de un solo paso sin herramientas externas — es un LLM funcionando como herramienta de productividad, no como agente.", "Identificar agentes vs herramientas"),
        q("¿Qué principio de diseño de agentes mitiga mejor el riesgo de errores con consecuencias irreversibles?", ["Usar el LLM más inteligente disponible", "Human-in-the-loop para acciones de alto impacto: requerir aprobación humana antes de ejecutar acciones con consecuencias significativas o difícilmente reversibles", "Usar más memoria", "Ejecutar múltiples agentes en paralelo para votación"], 1, "Human-in-the-loop (HITL) es el principio de diseño más importante para agentes en producción. No todas las acciones necesitan aprobación — enviar un mensaje interno, crear un borrador, hacer una búsqueda son generalmente seguros. Pero enviar un email externo a un cliente, hacer una transacción financiera, eliminar datos, o publicar contenido en redes sociales deberían requerir revisión humana. HITL te da el valor de la automatización con la seguridad del juicio humano donde importa.", "Human-in-the-loop en agentes"),
        q("¿Qué hace que Claude Computer Use (2024) sea significativo para los agentes?", ["Es más barato", "Permite a Claude controlar directamente un navegador y computadora real, ejecutando cualquier tarea que un humano haría con esos instrumentos", "Es más rápido", "Solo funciona en Mac"], 1, "Claude Computer Use representa un salto cualitativo: en lugar de que el agente use APIs específicas para cada herramienta, puede controlar directamente la interfaz visual de cualquier aplicación que un humano usaría. Puede navegar cualquier sitio web, usar cualquier software de escritorio, interactuar con formularios y sistemas legacy. Esto elimina la necesidad de APIs específicas para cada herramienta y abre la automatización a sistemas que no tienen API.", "Claude Computer Use")
      ],
      practica: {
        tipo: "caso_real",
        contexto: "Eres AI Engineer en una agencia de marketing digital. El equipo de social media pasa 2 horas diarias haciendo: monitoreo de menciones de marca en Twitter/X, identificando las que requieren respuesta, redactando respuestas, y publicándolas. Te piden automatizar el proceso.",
        instruccion: "Diseña un agente para este proceso. Especifica: qué herramientas necesita, qué pasos ejecuta autónomamente, dónde requiere aprobación humana, y qué riesgos mitigas con ese diseño.",
        input_malo: "El agente monitorea, redacta Y publica respuestas automáticamente sin supervisión humana para maximizar velocidad.",
        pista: "Una respuesta incorrecta o inapropiada de la marca en redes sociales puede ir viral de forma negativa. ¿Cuál es el peor escenario posible si el agente comete un error?",
        solucion: "Diseño del agente con HITL estratégico: Herramientas del agente: API de Twitter para lectura de menciones, clasificador de sentimiento/urgencia, base de conocimiento de la marca (tono, FAQs, políticas), servicio de notificación para el equipo, y API de Twitter para ESCRITURA (solo con aprobación). Flujo autónomo (sin aprobación): 1. Monitorea menciones cada 15 minutos. 2. Clasifica por tipo (queja, pregunta, elogio, neutral) y urgencia. 3. Filtra menciones que no requieren respuesta. 4. Para las que requieren respuesta, genera un borrador personalizado. 5. Notifica al equipo con la mención + borrador + clasificación. Human-in-the-loop obligatorio: El equipo revisa el borrador, lo edita si necesita, y aprueba antes de publicar. Justificación del HITL: Una respuesta de marca mal redactada puede viralizarse negativamente, afectar la reputación, y costar más en relaciones públicas de lo que ahorró la automatización. Resultado: El agente automatiza el 80% del trabajo (monitoreo, clasificación, borradores) y el humano hace el 20% de alto valor (juicio editorial y aprobación final). Tiempo estimado: de 2 horas a 30 minutos diarios.",
        criterios_de_exito: [
          "Diseña el agente con HITL específico en el punto de publicación",
          "Justifica el HITL con el análisis de riesgo del peor escenario",
          "Especifica qué partes son completamente autónomas y por qué esas son seguras"
        ]
      },
      conexion: { siguiente_concepto: "El mapa visual del ecosistema completo de IA en 2026", por_que_importa_despues: "Con todos los tipos de IA claros, es momento de ver el ecosistema completo — todos los jugadores, herramientas y cómo se relacionan." }
    }
  },
  'l10': {
    id: "m1-b1-l10", titulo: "El mapa visual del ecosistema completo de IA en 2026", bloque: 1,
    tipo: "leccion", duracion_min: 20, xp: 50,
    contenido: {
      teoria: {
        explicacion: `Para tomar decisiones inteligentes sobre qué aprender, qué herramientas usar y dónde posicionarte profesionalmente, necesitas una visión del ecosistema completo de IA en 2026. Este mapa tiene 5 capas que van desde la infraestructura física hasta las aplicaciones que los usuarios finales usan.

Capa 1 — Hardware e Infraestructura Compute: NVIDIA domina con sus GPUs (H100, H200, Blackwell). AWS, Google Cloud, y Azure son los principales proveedores de cómputo en la nube para IA. Microsoft, Google y Amazon compiten por ser el proveedor preferido de infraestructura para entrenar y desplegar modelos. Esta capa es donde se gasta el dinero más grande — entrenar un modelo de frontera cuesta cientos de millones de dólares.

Capa 2 — Modelos Fundacionales: Los laboratorios que entrenan los modelos base. Anthropic (Claude), OpenAI (GPT-4o, o1), Google (Gemini), Meta (LLaMA), Mistral, y una docena de laboratorios más pequeños. Estos modelos son la materia prima del ecosistema. Tienen capacidades que ninguna empresa individual podría replicar sin inversiones masivas. Para el 99% de los AI Engineers, el trabajo comienza en esta capa, no por debajo.

Capa 3 — Frameworks y Plataformas: Las herramientas que permiten construir aplicaciones sobre los modelos fundacionales. LangChain y LlamaIndex para orquestación de LLMs. Hugging Face como hub de modelos open source. Pinecone, Weaviate y pgvector para bases de datos vectoriales. Weights & Biases para experiment tracking. Esta capa está en constante cambio — los frameworks populares de 2023 pueden quedar obsoletos en 2024.

Capa 4 — IDEs y Herramientas de Desarrollo Aumentado con IA: Cursor, Windsurf, GitHub Copilot (para desarrollo de software). Perplexity (búsqueda con IA). Notion AI, Grammarly (productividad). Esta capa está transformando el trabajo de los developers: un developer con Cursor + Claude Code es 2-4x más productivo que sin ellas.

Capa 5 — Aplicaciones y Verticales: Las herramientas de usuario final para industrias específicas. Jasper (marketing), Harvey (legal), Nabla (salud), Klarna (finanzas). En LATAM, la oportunidad está en construir estas aplicaciones verticales para mercados locales donde los grandes jugadores globales no están adaptados.

Los jugadores estratégicos clave en 2026: Anthropic: Referente en seguridad, Constitutional AI, Claude Code, y APIs para empresas. Fuerte en casos de uso de alto stakes. OpenAI: La marca más reconocida, ecosistema de plugins, integración con Microsoft 365. Google: Gemini integrado en todos los productos de Google, ventaja en búsqueda en tiempo real, Google Workspace. Meta: LLaMA como open source — permite correr modelos localmente sin API, crítico para casos de privacidad. Mistral: La alternativa europea, modelos eficientes, open source.

Para AI Engineers en LATAM: Las mejores oportunidades están en la Capa 5 (aplicaciones verticales), usando las Capas 2 y 3 como infraestructura. No necesitas competir con los grandes laboratorios — construyes sobre su trabajo para resolver problemas específicos de tu mercado.`,
        analogia: "El ecosistema de IA es como el ecosistema del automóvil: hay quienes minan el acero (hardware), quienes fabrican motores (modelos fundacionales), quienes diseñan las fábricas (frameworks), quienes construyen los autos (apps) y quienes los manejan (usuarios). Tú como AI Engineer probablemente construyes autos, no minas acero.",
        ejemplo_malo: "Intentar competir en la Capa 2 (entrenar modelos fundacionales) sin capital de cientos de millones de dólares y equipo de cientos de investigadores — una startup no puede ganar ahí.",
        ejemplo_bueno: "Construir una aplicación vertical (Capa 5) usando Claude API (Capa 2) y LlamaIndex (Capa 3) para automatizar procesos legales en Colombia — donde hay ventaja de conocimiento local y los grandes players no tienen presencia.",
        por_que_importa: "Conocer el ecosistema te ayuda a elegir en qué parte posicionarte, qué herramientas elegir para qué propósito, y dónde están las oportunidades de negocio reales para tu perfil y ubicación.",
        tip_profesional: "Suscríbete a The Rundown AI y AI Breakfast (newsletters gratuitas) para mantenerte al día con la Capa 3 (frameworks) y Capa 5 (aplicaciones). Puedes estudiar las Capas 1 y 2 más profundamente con menor frecuencia, porque cambian más lentamente."
      },
      verificacion: [
        q("¿En qué capa del ecosistema de IA debería enfocarse la mayoría de los AI Engineers en LATAM para maximizar su impacto?", ["Capa 1: Hardware e infraestructura", "Capa 5: Aplicaciones verticales para mercados locales, usando Capas 2 y 3 como infraestructura", "Capa 2: Entrenamiento de modelos fundacionales", "Capa 3: Desarrollo de frameworks"], 1, "La Capa 5 es donde está la oportunidad para AI Engineers en LATAM porque: (1) requiere conocimiento local que los grandes players globales no tienen, (2) no requiere capital masivo para competir, (3) los problemas de negocio locales están bien definidos y los clientes están dispuestos a pagar. La Capa 2 requiere cientos de millones y equipos de cientos de researchers. La Capa 3 está dominada por jugadores bien financiados con bases de usuarios establecidas.", "Oportunidades para AI Engineers en LATAM"),
        q("¿Qué representa la Capa 3 (Frameworks y Plataformas) y por qué es la capa que cambia más rápido?", ["Hardware de NVIDIA — cambia con cada generación de chip", "Herramientas como LangChain, bases vectoriales y Hugging Face que permiten construir sobre modelos fundacionales — cambian rápido porque el mercado de herramientas es muy competitivo y la tecnología subyacente evoluciona rápido", "Los modelos de OpenAI y Anthropic", "Las aplicaciones de usuario final"], 1, "Los frameworks de la Capa 3 tienen alta volatilidad porque: están construidos sobre modelos que cambian (y deben actualizarse), el mercado es competitive y los ganadores cambian, y la comunidad open source innova rápidamente. LangChain era dominante en 2023, muchos proyectos lo reemplazaron en 2024 con alternativas más simples. Por eso, en esta capa se aprende el concepto (orquestación de LLMs) más que la herramienta específica.", "Volatilidad de la Capa 3"),
        q("¿Cuál es la ventaja estratégica de Meta con LLaMA en el ecosistema de IA?", ["Es el modelo más inteligente", "LLaMA es open source, lo que permite correr modelos localmente sin API externa — crítico para casos donde la privacidad de datos o los costos de API son restricciones", "Es gratuito para todas las empresas", "Tiene mejor interfaz de usuario"], 1, "La ventaja de LLaMA no es ser el mejor modelo sino ser open source y corrível localmente. Esto lo hace crítico para: sectores con datos sensibles (salud, legal, gobierno) donde enviar datos a APIs externas es problemático, empresas que necesitan control total sobre sus datos, casos donde el volumen de inferencia hace las APIs demasiado caras, y developers que quieren experimentar sin costo de API. Ollama permite correr LLaMA y otros modelos en una laptop moderna.", "Ventaja estratégica de LLaMA"),
        q("¿Por qué Anthropic se destaca en el ecosistema a pesar de no tener la marca más reconocida?", ["Por ser la empresa más antigua", "Por su enfoque en seguridad (Constitutional AI), rendimiento en tareas de largo contexto, y Claude Code para AI Engineers", "Por ser la más barata", "Por tener más usuarios"], 1, "Anthropic se distingue por su investigación en AI Safety y Constitutional AI, que resulta en modelos que son más consistentes, menos propensos a jailbreak, y más confiables para casos de uso empresariales de alto stakes. Claude tiene la ventana de contexto más grande del mercado en varios modelos, crítico para análisis de documentos largos. Claude Code (2025) está redefiniendo el desarrollo de software asistido por IA para un segmento técnico sofisticado.", "Posicionamiento de Anthropic"),
        q("¿Qué distingue a las aplicaciones de Capa 5 (verticales) de los modelos fundacionales de Capa 2?", ["Las aplicaciones son más baratas de entrenar", "Las aplicaciones resuelven problemas específicos de industria o mercado local usando los modelos fundacionales como infraestructura — requieren conocimiento del dominio más que capital masivo", "Los modelos fundacionales son más inteligentes", "Las aplicaciones no necesitan IA"], 1, "La distinción es similar a la diferencia entre construir una autopista (Capa 2) y construir un servicio de taxi (Capa 5). Los modelos fundacionales requieren capital masivo y son de propósito general. Las aplicaciones verticales requieren conocimiento profundo del problema específico, relaciones con el cliente, y capacidad de customizar la solución — ventajas que los grandes laboratorios no tienen por su naturaleza de propósito general.", "Diferencia entre Capas 2 y 5")
      ],
      practica: {
        tipo: "caso_real",
        contexto: "Eres AI Engineer freelance en Colombia y quieres construir un negocio de consultoría de IA. Tienes 6 meses para posicionarte. El ecosistema local incluye muchas pymes que no han implementado IA, algunas empresas medianas con proyectos piloto, y pocas grandes empresas con equipos de datos.",
        instruccion: "Usando el mapa de capas del ecosistema, define en qué capa(s) te enfocarás, qué oportunidad específica atacarás primero, y por qué esa elección tiene sentido dado tu contexto.",
        input_malo: "Voy a entrenar mi propio modelo de lenguaje para el mercado colombiano — los modelos actuales no están adaptados a Colombia.",
        pista: "¿Qué capa requiere menos capital inicial? ¿Dónde tu conocimiento del mercado local es una ventaja vs un player global? ¿Qué tipo de cliente tiene más capacidad de pago y más urgencia?",
        solucion: "Foco en Capa 5 con especialización vertical: Elección: Aplicaciones para el sector legal colombiano. Justificación: (1) El derecho colombiano es específico (código civil vs common law, normativa local) — los LLMs globales no están optimizados para esto. (2) Las firmas legales tienen dinero, tienen problema claro (revisión de contratos es tiempo intensivo), y están empezando a explorar IA. (3) No compito con OpenAI ni Anthropic — construyo SOBRE ellos. Stack técnico: Claude API (Capa 2) + bases vectoriales para documentos legales colombianos (Capa 3) + interfaz web simple (Capa 5). Propuesta de valor: 'Revisión de contratos bajo derecho colombiano 5x más rápido con IA'. Primer cliente: una firma de 10-20 abogados dispuesta a ser referencia. En 6 meses: 3-5 clientes, caso de estudio documentado, posicionamiento como 'el AI Engineer que entiende el sector legal colombiano'.",
        criterios_de_exito: [
          "Elige correctamente la Capa 5 (no intenta competir en Capa 2)",
          "Identifica una vertical específica con ventaja de conocimiento local",
          "Define el primer cliente y propuesta de valor concreta"
        ]
      },
      conexion: { siguiente_concepto: "Por qué necesitas matemáticas y cuántas exactamente", por_que_importa_despues: "Con el mapa del ecosistema claro, entramos a las herramientas matemáticas que te permiten entender cómo funcionan los modelos desde adentro." }
    }
  }
}

// Reemplazar los slots vacíos en b1 (índices 4-9)
Object.keys(nuevas).forEach(key => {
  const idx = { l5: 4, l6: 5, l7: 6, l8: 7, l9: 8, l10: 9 }[key]
  b1.lecciones[idx] = nuevas[key]
})

fs.writeFileSync(file, JSON.stringify(data, null, 2))
const reales = b1.lecciones.filter(l => l.contenido.teoria.explicacion !== 'PENDIENTE DE GENERAR').length
console.log(`B1 completado: ${reales}/10 lecciones con contenido real`)
